import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Car, CheckCircle2, CreditCard, MapPin, MessageCircle } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { useI18n } from "@/lib/i18n";
import { useSession } from "@/lib/auth";
import { useOffers, usePackages, useProfile, useSettings } from "@/lib/data";

export const Route = createFileRoute("/book")({
  validateSearch: (search) => ({ type: typeof search.type === "string" ? search.type : "package", id: typeof search.id === "string" ? search.id : "" }),
  component: BookingPage,
});

type FormState = { date:string; time:string; wash_type:string; full_name:string; phone:string; email:string; car_type:string; brand:string; model:string; color:string; plate:string; address:string; location_url:string; notes:string; payment_method:string };
const today = new Date().toISOString().slice(0,10);
const initial: FormState = { date:today,time:"",wash_type:"car_wash",full_name:"",phone:"",email:"",car_type:"",brand:"",model:"",color:"",plate:"",address:"",location_url:"",notes:"",payment_method:"cash" };

function BookingPage(){
 const {pick,fmtMoney}=useI18n(); const {type,id}=Route.useSearch(); const {user}=useSession();
 const {data:profile}=useProfile(user?.id); const {data:settings}=useSettings(); const {data:packages}=usePackages(); const {data:offers}=useOffers();
 const s:any=settings; const [form,setForm]=useState<FormState>(initial); const [booked,setBooked]=useState<string[]>([]); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [done,setDone]=useState(false);
 const item:any=type==="offer"?(offers??[]).find((x:any)=>x.id===id):(packages??[]).find((x:any)=>x.id===id); const price=type==="offer"?Number(item?.new_price??item?.old_price??0):Number(item?.price??0); const title=item?pick(item.title_en,item.title_ar):pick("Selected service","الخدمة المختارة");
 const start=(s?.booking_start_time??"09:00:00").slice(0,5), end=(s?.booking_end_time??"21:00:00").slice(0,5), step=Number(s?.booking_slot_minutes??60);
 useEffect(()=>{if(profile)setForm(f=>({...f,full_name:profile.full_name??"",phone:profile.phone??"",email:profile.email??user?.email??""}))},[profile,user?.email]);
 useEffect(()=>{let live=true;(async()=>{if(!form.date)return;setLoading(true);const a=new Date(`${form.date}T00:00:00`).toISOString(),b=new Date(`${form.date}T23:59:59`).toISOString();const {data,error}=await(supabase as any).rpc("get_booked_booking_slots",{p_start:a,p_end:b});if(live){if(error)toast.error(error.message);setBooked((data??[]).map((x:any)=>new Date(x.scheduled_at).toTimeString().slice(0,5)));setLoading(false)}})();return()=>{live=false}},[form.date]);
 const slots=useMemo(()=>{const r:string[]=[];let [h,m]=start.split(":").map(Number);const [eh,em]=end.split(":").map(Number),stop=eh*60+em;while(h*60+m<stop){r.push(`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`);m+=step;h+=Math.floor(m/60);m%=60}return r},[start,end,step]);
 const set=(k:keyof FormState,v:string)=>setForm(f=>({...f,[k]:v}));
 const submit=async()=>{if(!user||!item)return;if(!form.date||!form.time||!form.full_name||!form.phone||!form.car_type||!form.address)return toast.error(pick("Complete all required details.","اكمل البيانات المطلوبة."));const when=new Date(`${form.date}T${form.time}:00`);const {data:exists}=await(supabase as any).rpc("get_booked_booking_slots",{p_start:new Date(when.getTime()-1000).toISOString(),p_end:new Date(when.getTime()+1000).toISOString()});if((exists??[]).length)return toast.error(pick("This time is already booked.","الموعد ده اتحجز، اختار موعد تاني."));setSaving(true);let carId=null;const {data:car}=await(supabase as any).from("cars").insert({customer_id:user.id,brand:form.brand||null,model:form.model||null,color:form.color||null,plate_number:form.plate||null,notes:form.car_type}).select("id").single();if(car)carId=car.id;const {error}=await(supabase as any).from("booking_requests").insert({customer_id:user.id,package_id:type==="package"?id:null,offer_id:type==="offer"?id:null,car_id:carId,wash_type:form.wash_type,scheduled_at:when.toISOString(),customer_name:form.full_name,customer_phone:form.phone,customer_email:form.email||user.email,car_type:form.car_type,car_brand:form.brand,car_model:form.model,car_color:form.color,plate_number:form.plate,address:form.address,location_url:form.location_url||null,notes:form.notes||null,amount:price,payment_method:form.payment_method,payment_status:form.payment_method==="cash"?"unpaid":"awaiting_proof",status:"pending"});setSaving(false);if(error)return toast.error(error.code==="23505"?pick("This time was just booked.","الموعد اتحجز للتو."):error.message);setDone(true);if(form.payment_method!=="cash"){const wa=String(s?.whatsapp??s?.phone??"").replace(/\D/g,"");if(wa)window.open(`https://wa.me/${wa}?text=${encodeURIComponent(pick(`Hello TapWash, I confirmed payment for ${title}. Appointment: ${form.date} ${form.time}. Amount: ${price} EGP. I will send the payment screenshot now.`,`مرحباً TapWash، أكدت الدفع لـ ${title}. موعد الغسيل: ${form.date} ${form.time}. المبلغ: ${price} جنيه. سأرسل سكرين التحويل الآن.`))}`,"_blank","noopener,noreferrer")}};
 if(!user)return <div className="mx-auto max-w-xl px-4 py-20 text-center"><h1 className="text-2xl font-bold">{pick("Login required","لازم تسجل دخول")}</h1><Button asChild className="mt-6"><Link to="/login">{pick("Login","تسجيل الدخول")}</Link></Button></div>;
 if(done)return <div className="mx-auto max-w-2xl px-4 py-20"><div className="panel p-8 text-center"><CheckCircle2 className="mx-auto size-14 text-primary"/><h1 className="mt-4 text-2xl font-bold">{pick("Booking request sent","تم إرسال طلب الحجز")}</h1><p className="mt-3 text-muted-foreground">{pick("The request is now visible to management for confirmation.","الطلب ظهر للمدير لمراجعته وتأكيده.")}</p>{form.payment_method!=="cash"&&<div className="mt-5 rounded-xl border p-4 text-sm"><MessageCircle className="mx-auto mb-2 size-6 text-primary"/>{pick("Send the payment screenshot to the WhatsApp number listed on the site.","ابعت سكرين التحويل على رقم واتساب الموجود في الموقع.")}</div>}<Button asChild className="mt-6"><Link to="/dashboard">{pick("Back to dashboard","العودة للوحة العميل")}</Link></Button></div></div>;
 return <div className="min-h-screen bg-background"><div className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><div className="mb-8"><Badge>{type==="offer"?pick("Offer","عرض"):pick("Package","باقة")}</Badge><h1 className="mt-3 text-3xl font-bold">{title}</h1><p className="mt-2 text-muted-foreground">{item?.description_en?pick(item.description_en,item.description_ar):""}</p><p className="mt-4 text-3xl font-extrabold text-primary">{fmtMoney(price)}</p></div>
 <div className="grid gap-6 lg:grid-cols-2"><section className="panel p-6"><h2 className="flex items-center gap-2 text-lg font-bold"><CalendarDays className="size-5 text-primary"/>{pick("Choose appointment","اختار موعد الغسيل")}</h2><div className="mt-5 space-y-4"><div className="space-y-2"><Label>{pick("Date","التاريخ")}</Label><Input type="date" min={today} value={form.date} onChange={e=>set("date",e.target.value)}/></div><div className="space-y-2"><Label>{pick("Available time","الوقت المتاح")}</Label><div className="grid grid-cols-3 gap-2">{loading?<span className="col-span-3 text-sm text-muted-foreground">{pick("Loading...","جاري التحميل...")}</span>:slots.map(x=>{const off=booked.includes(x);return <Button key={x} type="button" disabled={off} variant={form.time===x?"default":"outline"} onClick={()=>set("time",x)}>{x}{off?" · محجوز":""}</Button>})}</div></div><div className="space-y-2"><Label>{pick("Wash type","نوع الغسيل")}</Label><select className="h-10 w-full rounded-md border bg-background px-3" value={form.wash_type} onChange={e=>set("wash_type",e.target.value)}><option value="car_wash">{pick("Car wash","غسيل سيارة")}</option><option value="interior">{pick("Interior","داخلي")}</option><option value="exterior">{pick("Exterior","خارجي")}</option><option value="full">{pick("Full","كامل")}</option></select></div></div></section>
 <section className="panel p-6"><h2 className="flex items-center gap-2 text-lg font-bold"><Car className="size-5 text-primary"/>{pick("Customer & car","بيانات العميل والسيارة")}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{([["full_name","Full name","الاسم"],["phone","Contact phone","رقم التواصل"],["car_type","Car type","نوع العربية"],["brand","Brand","الماركة"],["model","Model","الموديل"],["color","Color","اللون"],["plate","Plate number","رقم اللوحة"]] as const).map(([k,en,ar])=><div key={k} className="space-y-2"><Label>{pick(en,ar)}</Label><Input value={form[k]} onChange={e=>set(k,e.target.value)}/></div>)}<div className="space-y-2 sm:col-span-2"><Label>{pick("Address","العنوان")}</Label><div className="flex gap-2"><MapPin className="mt-2 size-5 text-primary"/><Input value={form.address} onChange={e=>set("address",e.target.value)}/></div></div><div className="space-y-2 sm:col-span-2"><Label>{pick("Map link","لينك الموقع")}</Label><Input value={form.location_url} onChange={e=>set("location_url",e.target.value)} placeholder="https://maps.google.com/..."/></div><div className="space-y-2 sm:col-span-2"><Label>{pick("Notes","ملاحظات")}</Label><Textarea value={form.notes} onChange={e=>set("notes",e.target.value)}/></div></div></section></div>
 <section className="panel mt-6 p-6"><h2 className="flex items-center gap-2 text-lg font-bold"><CreditCard className="size-5 text-primary"/>{pick("Payment method","طريقة الدفع")}</h2><div className="mt-4 flex flex-wrap gap-3"><Button type="button" variant={form.payment_method==="cash"?"default":"outline"} onClick={()=>set("payment_method","cash")}>{pick("Cash on service","دفع عند الغسيل")}</Button>{s?.smart_wallet_number&&<Button type="button" variant={form.payment_method==="smart_wallet"?"default":"outline"} onClick={()=>set("payment_method","smart_wallet")}>{pick("Smart Wallet","محفظة ذكية")}</Button>}{s?.instapay_number&&<Button type="button" variant={form.payment_method==="instapay"?"default":"outline"} onClick={()=>set("payment_method","instapay")}>{pick("InstaPay","إنستا باي")}</Button>}{s?.bank_account_number&&<Button type="button" variant={form.payment_method==="bank_transfer"?"default":"outline"} onClick={()=>set("payment_method","bank_transfer")}>{pick("Bank transfer","تحويل بنكي")}</Button>}</div>{form.payment_method!=="cash"&&<div className="mt-5 rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm"><b>{pick("Transfer details","بيانات التحويل")}</b>{form.payment_method==="smart_wallet"&&<p className="mt-2">{s?.smart_wallet_number}</p>}{form.payment_method==="instapay"&&<p className="mt-2">{s?.instapay_number}</p>}{form.payment_method==="bank_transfer"&&<div className="mt-2 space-y-1"><p>{s?.bank_name}</p><p>{s?.bank_account_name}</p><p>{s?.bank_account_number}</p><p>{s?.bank_iban}</p></div>}<p className="mt-3 text-muted-foreground">{pick("After confirming payment, send the screenshot to the WhatsApp number listed on the site.","بعد تأكيد الدفع ابعت سكرين التحويل على رقم واتساب الموجود في الموقع.")}</p></div>}<Button size="lg" className="mt-6 w-full" onClick={submit} disabled={saving||!form.time}>{saving?pick("Sending...","جاري الإرسال..."):pick("Confirm booking","تأكيد الحجز")}</Button></section>
 </div></div>;
}
