import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Car, CheckCircle2, CreditCard, MapPin, MessageCircle, PackageCheck } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { useI18n } from "@/lib/i18n";
import { useSession } from "@/lib/auth";
import { useOffers, usePackages, useProfile, useSettings } from "@/lib/data";

export const Route = createFileRoute("/book")({
  validateSearch: (search) => ({ type: typeof search.type === "string" ? search.type : "package", id: typeof search.id === "string" ? search.id : "" }),
  component: BookingPage,
});

type FormState = { date:string; time:string; wash_type:string; full_name:string; phone:string; email:string; car_type:string; brand:string; model:string; color:string; plate:string; address:string; location_url:string; notes:string; payment_method:string };
const today = new Date().toISOString().slice(0,10);
const initial: FormState = { date:today,time:"",wash_type:"car_wash",full_name:"",phone:"",email:"",car_type:"",brand:"",model:"",color:"",plate:"",address:"",location_url:"",notes:"",payment_method:"cash" };

function BookingPage(){
 const {pick,fmtMoney}=useI18n(); const {type,id}=Route.useSearch(); const {user}=useSession();
 const {data:profile}=useProfile(user?.id); const {data:settings}=useSettings(); const {data:packages}=usePackages(); const {data:offers}=useOffers();
 const s:any=settings; const isSubscription=type==="subscription"; const [form,setForm]=useState<FormState>(initial); const [booked,setBooked]=useState<string[]>([]); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [done,setDone]=useState(false);
 const item:any=type==="offer"?(offers??[]).find((x:any)=>x.id===id):(packages??[]).find((x:any)=>x.id===id); const price=type==="offer"?Number(item?.new_price??item?.old_price??0):Number(item?.price??0); const title=item?pick(item.title_en,item.title_ar):pick("Selected service","الخدمة المختارة");
 const start=(s?.booking_start_time??"09:00:00").slice(0,5), end=(s?.booking_end_time??"21:00:00").slice(0,5), step=Number(s?.booking_slot_minutes??60);
 useEffect(()=>{if(profile)setForm(f=>({...f,full_name:profile.full_name??"",phone:profile.phone??"",email:profile.email??user?.email??""}))},[profile,user?.email]);
 useEffect(()=>{if(isSubscription)return;let live=true;(async()=>{if(!form.date)return;setLoading(true);const a=new Date(`${form.date}T00:00:00`).toISOString(),b=new Date(`${form.date}T23:59:59`).toISOString();const {data,error}=await(supabase as any).rpc("get_booked_booking_slots",{p_start:a,p_end:b});if(live){if(error)toast.error(error.message);setBooked((data??[]).map((x:any)=>new Date(x.scheduled_at).toTimeString().slice(0,5)));setLoading(false)}})();return()=>{live=false}},[form.date,isSubscription]);
 const slots=useMemo(()=>{const r:string[]=[];let [h,m]=start.split(":").map(Number);const [eh,em]=end.split(":").map(Number),stop=eh*60+em;while(h*60+m<stop){r.push(`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`);m+=step;h+=Math.floor(m/60);m%=60}return r},[start,end,step]);
 const set=(k:keyof FormState,v:string)=>setForm(f=>({...f,[k]:v}));
 const paymentConfigured=(method:string)=>method==="cash"||(method==="smart_wallet"&&!!s?.smart_wallet_number)||(method==="instapay"&&!!s?.instapay_number)||(method==="bank_transfer"&&!!s?.bank_account_number);
 const openWhatsApp=(message:string)=>{if(typeof window==="undefined")return;const raw=String(s?.whatsapp??"").replace(/\D/g,"").replace(/^00/,"");const number=raw.startsWith("20")?raw:raw.startsWith("0")?`20${raw.slice(1)}`:raw;if(!number)return;const a=document.createElement("a");a.href=`https://wa.me/${number}?text=${encodeURIComponent(message)}`;a.target="_blank";a.rel="noopener noreferrer";a.click();};
 const paymentWhatsAppMessage=()=>`مرحباً TapWash، أنا ${form.full_name}. أرسلت طلب ${isSubscription?`اشتراك في باقة ${title}`:"حجز"}. طريقة الدفع: محفظة ذكية. المبلغ: ${price} جنيه. رقم الهاتف: ${form.phone}. أرسل إثبات الدفع هنا لتأكيد الطلب.`;
 const submit=async()=>{
   if(!user||!item)return;
   if(!form.full_name||!form.phone||!form.car_type||!form.address)return toast.error(pick("Complete all required customer and car details.","اكمل بيانات العميل والسيارة المطلوبة."));
   if(!paymentConfigured(form.payment_method))return toast.error(pick("This payment method is not configured yet.","طريقة الدفع دي لسه مش متفعلة."));
   setSaving(true);
   let carId=null;
   const {data:car,error:carError}=await(supabase as any).from("cars").insert({customer_id:user.id,brand:form.brand||null,model:form.model||null,color:form.color||null,plate_number:form.plate||null,notes:form.car_type}).select("id").single();
   if(carError){setSaving(false);return toast.error(carError.message)}
   if(car)carId=car.id;
   if(isSubscription){
     const {error}=await(supabase as any).from("subscription_requests").insert({customer_id:user.id,package_id:id,car_id:carId,amount:price,payment_method:form.payment_method,payment_status:"pending",status:"pending",notes:[form.address,form.location_url,form.notes].filter(Boolean).join(" | ")||null});
     setSaving(false); if(error)return toast.error(error.message);
     if(form.payment_method==="smart_wallet")openWhatsApp(paymentWhatsAppMessage());
     setDone(true); return;
   }
   if(!form.date||!form.time){setSaving(false);return toast.error(pick("Choose a date and time.","اختار التاريخ والوقت."))}
   const when=new Date(`${form.date}T${form.time}:00`); const {data:exists}=await(supabase as any).rpc("get_booked_booking_slots",{p_start:new Date(when.getTime()-1000).toISOString(),p_end:new Date(when.getTime()+1000).toISOString()});
   if((exists??[]).length){setSaving(false);return toast.error(pick("This time is already booked.","الموعد ده اتحجز، اختار موعد تاني."))}
   const {error}=await(supabase as any).from("booking_requests").insert({customer_id:user.id,package_id:type==="package"?id:null,offer_id:type==="offer"?id:null,car_id:carId,wash_type:form.wash_type,scheduled_at:when.toISOString(),customer_name:form.full_name,customer_phone:form.phone,customer_email:form.email||user.email,car_type:form.car_type,car_brand:form.brand,car_model:form.model,car_color:form.color,plate_number:form.plate,address:form.address,location_url:form.location_url||null,notes:form.notes||null,amount:price,payment_method:form.payment_method,payment_status:form.payment_method==="cash"?"unpaid":"awaiting_proof",status:"pending"});
   setSaving(false); if(error)return toast.error(error.code==="23505"?pick("This time was just booked.","الموعد اتحجز للتو."):error.message); if(form.payment_method==="smart_wallet")openWhatsApp(paymentWhatsAppMessage()); setDone(true);
 };
 if(!user)return <div className="mx-auto max-w-xl px-4 py-20 text-center"><h1 className="text-2xl font-bold">{pick("Login required","لازم تسجل دخول")}</h1><Button asChild className="mt-6"><Link to="/login">{pick("Login","تسجيل الدخول")}</Link></Button></div>;
 if(done)return <div className="mx-auto max-w-2xl px-4 py-20"><div className="panel p-8 text-center"><CheckCircle2 className="mx-auto size-14 text-primary"/><h1 className="mt-4 text-2xl font-bold">{isSubscription?pick("Subscription request sent","تم إرسال طلب الاشتراك"):pick("Booking request sent","تم إرسال طلب الحجز")}</h1><p className="mt-3 text-muted-foreground">{isSubscription?pick("Your package request is now with management. Payment must be confirmed before the subscription is activated.","طلب الباقة وصل للإدارة، ولا يتم تفعيل الاشتراك إلا بعد تأكيد الدفع."):pick("The request is now visible to management for confirmation.","الطلب ظهر للمدير لمراجعته وتأكيده.")}</p>{isSubscription&&<div className="mt-5 rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm"><PackageCheck className="mx-auto mb-2 size-6 text-primary"/><p>{pick("The manager will confirm the payment and activate your subscription, then schedule your washes manually.","المدير هيؤكد الدفع ويفعل الاشتراك، وبعدها يحدد مواعيد الغسلات يدويًا.")}</p></div>}{form.payment_method!=="cash"&&<div className="mt-5 rounded-xl border p-4 text-sm"><MessageCircle className="mx-auto mb-2 size-6 text-primary"/>{pick("Send the payment proof to the WhatsApp number listed on the site.","ابعت إثبات التحويل على رقم واتساب الموجود في الموقع.")}</div>}<Button asChild className="mt-6"><Link to="/dashboard">{pick("Back to dashboard","العودة للوحة العميل")}</Link></Button></div></div>;
 return <div className="min-h-screen bg-background"><div className="mx-auto max-w-5xl px-4 py-10 sm:px-6"><div className="mb-8"><Badge>{isSubscription?pick("Subscription","اشتراك"):type==="offer"?pick("Offer","عرض"):pick("Package","باقة")}</Badge><h1 className="mt-3 text-3xl font-bold">{title}</h1><p className="mt-2 text-muted-foreground">{item?.description_en?pick(item.description_en,item.description_ar):""}</p><p className="mt-4 text-3xl font-extrabold text-primary">{fmtMoney(price)}</p>{isSubscription&&<p className="mt-2 text-sm text-muted-foreground">{pick(`${item?.washes_count??0} washes over ${item?.duration_days??30} days. The manager will set each wash date.`,`${item?.washes_count??0} غسلات خلال ${item?.duration_days??30} يوم، والمدير هيحدد تاريخ كل غسلة.`)}</p>}</div>
 {isSubscription?null:<section className="panel mb-6 p-6"><h2 className="flex items-center gap-2 text-lg font-bold"><CalendarDays className="size-5 text-primary"/>{pick("Choose appointment","اختار موعد الغسيل")}</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><div><Label>{pick("Date","التاريخ")}</Label><Input className="mt-2" type="date" min={today} value={form.date} onChange={e=>set("date",e.target.value)}/></div><div><Label>{pick("Available time","الوقت المتاح")}</Label><div className="mt-2 grid grid-cols-3 gap-2">{loading?<span className="col-span-3 text-sm text-muted-foreground">{pick("Loading...","جاري التحميل...")}</span>:slots.map(x=>{const off=booked.includes(x);return <Button key={x} type="button" disabled={off} variant={form.time===x?"default":"outline"} onClick={()=>set("time",x)}>{x}</Button>})}</div></div></div></section>}
 <section className="panel p-6"><h2 className="flex items-center gap-2 text-lg font-bold"><Car className="size-5 text-primary"/>{pick("Customer & car","بيانات العميل والسيارة")}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{([["full_name","Full name","الاسم"],["phone","Contact phone","رقم التواصل"],["car_type","Car type","نوع العربية"],["brand","Brand","الماركة"],["model","Model","الموديل"],["color","Color","اللون"],["plate","Plate number","رقم اللوحة"]] as const).map(([k,en,ar])=><div key={k} className="space-y-2"><Label>{pick(en,ar)}</Label><Input value={form[k]} onChange={e=>set(k,e.target.value)}/></div>)}<div className="space-y-2 sm:col-span-2"><Label>{pick("Address","العنوان")}</Label><div className="flex gap-2"><MapPin className="mt-2 size-5 text-primary"/><Input value={form.address} onChange={e=>set("address",e.target.value)}/></div></div><div className="space-y-2 sm:col-span-2"><Label>{pick("Map link","لينك الموقع")}</Label><Input value={form.location_url} onChange={e=>set("location_url",e.target.value)} placeholder="https://maps.google.com/..."/></div><div className="space-y-2 sm:col-span-2"><Label>{pick("Notes","ملاحظات")}</Label><Textarea value={form.notes} onChange={e=>set("notes",e.target.value)}/></div></div></section>
 <section className="panel mt-6 p-6"><h2 className="flex items-center gap-2 text-lg font-bold"><CreditCard className="size-5 text-primary"/>{pick("Payment method","طريقة الدفع")}</h2><p className="mt-2 text-sm text-muted-foreground">{pick("Choose how you want to pay. Management confirms the payment before activation.","اختار طريقة الدفع، والإدارة بتأكد الدفع قبل تفعيل الاشتراك.")}</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Button type="button" variant={form.payment_method==="cash"?"default":"outline"} onClick={()=>set("payment_method","cash")}>{pick("Cash","كاش")}</Button><Button type="button" variant={form.payment_method==="smart_wallet"?"default":"outline"} onClick={()=>set("payment_method","smart_wallet")}>{pick("Smart Wallet","محفظة ذكية")}</Button><Button type="button" variant={form.payment_method==="instapay"?"default":"outline"} onClick={()=>set("payment_method","instapay")}>InstaPay</Button><Button type="button" variant={form.payment_method==="bank_transfer"?"default":"outline"} onClick={()=>set("payment_method","bank_transfer")}>{pick("Bank transfer","تحويل بنكي")}</Button></div>{form.payment_method!=="cash"&&<div className="mt-5 rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm"><b>{pick("Transfer details","بيانات التحويل")}</b>{form.payment_method==="smart_wallet"&&<p className="mt-2">{s?.smart_wallet_number||pick("Not configured yet.","الإدارة لم تضف الرقم حتى الآن.")}</p>}{form.payment_method==="instapay"&&<p className="mt-2">{s?.instapay_number||pick("Not configured yet.","الإدارة لم تضف بيانات InstaPay حتى الآن.")}</p>}{form.payment_method==="bank_transfer"&&<div className="mt-2 space-y-1"><p>{s?.bank_name||""}</p><p>{s?.bank_account_name||""}</p><p>{s?.bank_account_number||""}</p><p>{s?.bank_iban||""}</p></div>}<p className="mt-3 text-muted-foreground">{pick("Send the payment proof to the WhatsApp number listed on the site.","ابعت إثبات التحويل على رقم واتساب الموجود في الموقع.")}</p></div>}<Button size="lg" className="mt-6 w-full" onClick={submit} disabled={saving||(!isSubscription&&!form.time)}>{saving?pick("Sending...","جاري الإرسال..."):isSubscription?pick("Request subscription","طلب الاشتراك"):pick("Confirm booking","تأكيد الحجز")}</Button></section>
 </div></div>;
}
