import { createFileRoute } from "@tanstack/react-router";
import { Archive, Search, CalendarDays, MapPin, UserRound, Droplets } from "lucide-react";
import { useMemo, useState } from "react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { useI18n } from "@/lib/i18n";

export const Route = createFileRoute("/_authenticated/admin/archive")({ component: AdminArchive });

function AdminArchive(){
 const {pick}=useI18n();
 const [date,setDate]=useState(""); const [search,setSearch]=useState(""); const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(false);
 const openLocation=(address:any,url:any,lat?:any,lng?:any)=>{const target=url||(lat!=null&&lng!=null?`https://www.google.com/maps/search/?api=1&query=${lat},${lng}`:address?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`:"");if(target)window.open(target,"_blank","noopener,noreferrer");};
 const load=async(requestedDate=date)=>{setLoading(true);try{
  await(supabase as any).rpc("expire_due_subscriptions"); const q=search.trim();
  const [tasksRes,bookingsRes,paymentsRes,subsRes,washesRes,profilesRes]=await Promise.all([
   supabase.from("employee_tasks").select("*").order("created_at",{ascending:false}),
   supabase.from("booking_requests").select("*").order("created_at",{ascending:false}),
   supabase.from("payments").select("*").order("created_at",{ascending:false}),
   (supabase as any).from("subscriptions").select("*, packages(title_en,title_ar,washes_count,duration_days,price)").in("status",["expired","cancelled"]).order("updated_at",{ascending:false}),
   supabase.from("washes").select("*").order("washed_at",{ascending:false}),
   supabase.from("profiles").select("id,full_name,phone,address_text,location_url,latitude,longitude")
  ]);
  const profiles=profilesRes.data??[]; const profile=(id:any)=>profiles.find((p:any)=>String(p.id)===String(id));
  let all=[...(tasksRes.data??[]).map(x=>({...x,_type:"order",_ref:x.serial_number||x.id})),...(bookingsRes.data??[]).map(x=>({...x,_type:"booking",_ref:x.id})),...(paymentsRes.data??[]).map(x=>({...x,_type:"payment",_ref:x.order_id||x.id})),...(subsRes.data??[]).map(x=>({...x,_type:"subscription",_ref:x.id,_washes:(washesRes.data??[]).filter((w:any)=>String(w.subscription_id)===String(x.id)),_tasks:(tasksRes.data??[]).filter((t:any)=>String(t.subscription_id)===String(x.id)),_customer:profile(x.customer_id)}))];
  if(requestedDate){const start=new Date(`${requestedDate}T00:00:00.000Z`).getTime(),end=new Date(`${requestedDate}T23:59:59.999Z`).getTime();all=all.filter(x=>{const created=x.updated_at||x.created_at||x.washed_at;const n=created?new Date(created).getTime():NaN;return Number.isFinite(n)&&n>=start&&n<=end;});}
  if(q){const normalized=q.toLowerCase();all=all.filter(x=>[x._ref,x.serial_number,x.id,x.order_id,x.customer_name,x.name,x.customer_phone,x.phone,x.customer_email,x.email,x.employee_id,x.employee_name,x.assigned_employee_id,x.assigned_employee_name,x.status,x.payment_status,x.title,x.package_name,x.service_address,x.service_location_url,x._customer?.full_name,x._customer?.phone,x._customer?.address_text,x.packages?.title_ar,x.packages?.title_en].filter(v=>v!=null).join(" ").toLowerCase().includes(normalized));}
  all.sort((a,b)=>new Date(b.updated_at||b.created_at||b.washed_at||0).getTime()-new Date(a.updated_at||a.created_at||a.washed_at||0).getTime()); setRows(all);
 }finally{setLoading(false);}};
 const filtered=useMemo(()=>rows,[rows]); const orders=filtered.filter(x=>x._type==="order"); const subscriptions=filtered.filter(x=>x._type==="subscription"); const others=filtered.filter(x=>x._type!=="order"&&x._type!=="subscription");
 return <div className="space-y-6"><div className="flex items-center gap-2"><Archive className="size-6 text-primary"/><div><h1 className="text-2xl font-bold">{pick("Archive & search","الأرشيف والبحث")}</h1><p className="text-sm text-muted-foreground">{pick("Expired subscriptions are archived with their service location, washes and employee tasks.","الاشتراك المنتهي ينتقل للأرشيف مع لوكيشن الطلب والغسلات والمهام المكلفة.")}</p></div></div>
 <div className="panel p-5"><div className="grid gap-3 md:grid-cols-[auto_1fr_auto]"><div className="relative"><CalendarDays className="absolute start-3 top-3 size-4 text-muted-foreground"/><Input type="date" className="ps-9" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="relative"><Search className="absolute start-3 top-3 size-4 text-muted-foreground"/><Input className="ps-9" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void load();}} placeholder={pick("Search by customer, phone, employee, package or order","ابحث باسم العميل أو الرقم أو الموظف أو الباقة أو الأوردر")}/></div><Button onClick={()=>void load()} disabled={loading}>{loading?pick("Loading...","جاري البحث..."):pick("Search","بحث")}</Button></div></div>
 <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-bold">{date||pick("All archive","كل الأرشيف")}</h2><span className="text-sm text-muted-foreground">{filtered.length} {pick("records","سجل")}</span></div>
 {subscriptions.map(x=>{const c=x._customer;const address=x.service_address||c?.address_text;const locationUrl=x.service_location_url||c?.location_url;const lat=x.service_latitude??c?.latitude;const lng=x.service_longitude??c?.longitude;return <article key={`subscription-${x.id}`} className="panel border-red-500/20 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">📦 {pick("Expired subscription","اشتراك منتهي")} #{String(x.id).slice(0,8)}</h3><p className="text-sm text-muted-foreground">{x.packages?pick(x.packages.title_en,x.packages.title_ar):pick("Package","باقة")} · {x.packages?.washes_count??x.total_washes??0} {pick("washes","غسلات")} · {x.packages?.duration_days??"—"} {pick("days","يوم")}</p></div><span className="rounded-full bg-red-500/10 px-3 py-1 text-xs">{x.status==="expired"?pick("Expired","منتهي"):pick("Cancelled","ملغى")}</span></div>
 <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl border p-3"><small className="text-muted-foreground">اسم العميل</small><p className="font-semibold">{c?.full_name||"—"}</p><p className="text-xs text-muted-foreground">{c?.phone||"—"}</p></div><div className="rounded-xl border p-3"><small className="text-muted-foreground">لوكيشن الطلب</small><p className="font-semibold">{address||"—"}</p>{(locationUrl||lat!=null||lng!=null||address)&&<Button size="sm" variant="ghost" className="px-0" onClick={()=>openLocation(address,locationUrl,lat,lng)}><MapPin className="me-1 size-3.5"/>فتح اللوكيشن</Button>}</div><div className="rounded-xl border p-3"><small className="text-muted-foreground">الغسلات</small><p className="font-semibold">{x.used_washes??0} / {x.total_washes??0}</p></div><div className="rounded-xl border p-3"><small className="text-muted-foreground">الفترة</small><p className="font-semibold">{x.start_date||"—"} → {x.end_date||"—"}</p></div></div>
 <div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-xl border p-4"><h4 className="flex items-center gap-2 font-bold"><Droplets className="size-4"/>الغسلات الخاصة بالاشتراك</h4><div className="mt-2 space-y-2">{(x._washes??[]).length?(x._washes??[]).map((w:any)=><div key={w.id} className="flex items-center justify-between rounded-lg bg-muted/40 px-3 py-2 text-sm"><span>{w.washed_at?new Date(w.washed_at).toLocaleString():"—"}</span><span>{w.branch||"—"}</span></div>):<p className="text-sm text-muted-foreground">لا توجد غسلات مسجلة.</p>}</div></div><div className="rounded-xl border p-4"><h4 className="flex items-center gap-2 font-bold"><UserRound className="size-4"/>مهام الموظفين المرتبطة بالاشتراك</h4><div className="mt-2 space-y-2">{(x._tasks??[]).length?(x._tasks??[]).map((task:any)=>{const emp=profile(task.employee_id);return <div key={task.id} className="rounded-lg bg-muted/40 px-3 py-2 text-sm"><div className="flex flex-wrap justify-between gap-2"><b>{task.title||"مهمة غسيل"}</b><span>{task.status||"—"}</span></div><div className="text-xs text-muted-foreground mt-1">الموظف: {emp?.full_name||task.employee_name||"—"} · Employee ID: {task.employee_id||"—"}</div><div className="text-xs text-muted-foreground mt-1">الباقة: {task.package_name||"—"} · المتبقي وقت التكليف: {task.remaining_washes??"—"}</div></div>}) : <p className="text-sm text-muted-foreground">لا توجد مهام مرتبطة.</p>}</div></div></div><div className="mt-3 text-xs text-muted-foreground">آخر تحديث: {x.updated_at?new Date(x.updated_at).toLocaleString():"—"}</div></article>})}
 {orders.map(x=><article key={`order-${x.id}`} className="panel p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-bold">🚗 #{x.serial_number||x.id}</h3><p className="text-sm text-muted-foreground">{x.title||pick("Order","أوردر")}</p></div><span className="rounded-full bg-muted px-3 py-1 text-xs">{x.status||"—"}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl border p-3"><small className="text-muted-foreground">اسم العميل</small><p className="font-semibold">{x.customer_name||"—"}</p></div><div className="rounded-xl border p-3"><small className="text-muted-foreground">رقم التليفون</small><p className="font-semibold">{x.customer_phone||"—"}</p></div><div className="rounded-xl border p-3"><small className="text-muted-foreground">نوع الباقة</small><p className="font-semibold">{x.package_name||x.offer_name||x.wash_type||"—"}</p></div><div className="rounded-xl border p-3"><small className="text-muted-foreground">المتبقي</small><p className="font-semibold">{x.remaining_washes!=null?`${x.remaining_washes} غسلة`:"—"}</p></div><div className="rounded-xl border p-3 sm:col-span-2"><small className="text-muted-foreground">الموظف المكلف</small><p className="font-semibold">{x.employee_name||x.assigned_employee_name||x.employee_full_name||"—"}</p><p className="text-xs text-muted-foreground mt-1">Employee ID: {x.employee_id||x.assigned_employee_id||"—"}</p></div><div className="rounded-xl border p-3 sm:col-span-2"><small className="text-muted-foreground">ملاحظات</small><p>{x.notes||"—"}</p></div></div></article>)}
 {others.map(x=><div key={`${x._type}-${x.id}`} className="rounded-xl border border-border p-3"><b>{x._type==="booking"?"📋":"💳"} #{x._ref}</b><span className="ms-2 text-sm text-muted-foreground">{x.customer_name||x.name||x.customer_phone||x.phone||x.email||x.amount||"—"}</span><span className="float-end text-sm text-muted-foreground">{x.status||"—"}</span></div>)}{!filtered.length&&<p className="text-sm text-muted-foreground">{pick("No records found.","لا توجد نتائج مطابقة للبحث.")}</p>}</section></div>;
}
