import { createFileRoute } from "@tanstack/react-router";
import { Camera, MapPinned, RefreshCw, Search, Truck } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { DeliveryMap } from "@/components/app/DeliveryMap";
import { supabase } from "@/integrations/supabase/client";
import { useI18n } from "@/lib/i18n";

export const Route = createFileRoute("/_authenticated/admin/live-orders")({ component: LiveOrdersPage });
type Task = Record<string, any>;
type Photo = { id: string; task_id: string; kind: string; url: string; created_at: string };
type Location = { task_id: string; employee_id: string; latitude: number; longitude: number; accuracy?: number | null; heading?: number | null; speed?: number | null; updated_at: string };
type Point = { lat: number; lng: number };
function parseCustomerLocation(task: Task): Point | null {
  const lat = Number(task?.latitude), lng = Number(task?.longitude);
  if (Number.isFinite(lat) && Number.isFinite(lng) && Math.abs(lat) <= 90 && Math.abs(lng) <= 180) return { lat, lng };
  const url = String(task?.location_url ?? ""); if (!url) return null;
  try { const decoded = decodeURIComponent(url); const candidates = [decoded.match(/@(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)/), decoded.match(/[?&](?:q|ll|query|center)=(-?\d+(?:\.\d+)?)[,%20]+(-?\d+(?:\.\d+)?)/i), decoded.match(/!3d(-?\d+(?:\.\d+)?)!4d(-?\d+(?:\.\d+)?)/)]; for (const match of candidates) { if (!match) continue; const a=Number(match[1]), b=Number(match[2]); if (Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a)<=90&&Math.abs(b)<=180) return {lat:a,lng:b}; } } catch {}
  return null;
}
function formatActualDate(value: any) { return value ? new Date(value).toLocaleString("ar-EG", { dateStyle: "medium", timeStyle: "short" }) : "—"; }
function LiveOrdersPage() {
  const { fmtDate } = useI18n(); const [tasks,setTasks]=useState<Task[]>([]); const [photos,setPhotos]=useState<Photo[]>([]); const [locations,setLocations]=useState<Location[]>([]); const [selected,setSelected]=useState<string|null>(null); const [query,setQuery]=useState(""); const [refreshing,setRefreshing]=useState(false);
  const load=async()=>{ const [{data:td,error:te},{data:pd,error:pe},{data:ld,error:le}]=await Promise.all([(supabase as any).from("employee_tasks").select("*").order("updated_at",{ascending:false}).limit(100),(supabase as any).from("order_photos").select("id,task_id,kind,url,created_at").order("created_at",{ascending:false}).limit(500),(supabase as any).from("employee_locations").select("task_id,employee_id,latitude,longitude,accuracy,heading,speed,updated_at").limit(100)]); if(te)toast.error(te.message);if(pe)toast.error(pe.message);if(le)toast.error(le.message);setTasks(td??[]);setPhotos(pd??[]);setLocations(ld??[]);return !te&&!pe&&!le; };
  useEffect(()=>{void load();const ch=supabase.channel("manager-live-orders-page").on("postgres_changes",{event:"*",schema:"public",table:"employee_tasks"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"order_photos"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"employee_locations"},(payload:any)=>{const row=payload.new as Location;if(!row?.task_id)return;setLocations(c=>[...c.filter(i=>i.task_id!==row.task_id),row]);}).subscribe();return()=>{void supabase.removeChannel(ch)}},[]);
  const refresh=async()=>{setRefreshing(true);const ok=await load();setRefreshing(false);if(ok)toast.success("تم تحديث الأوردرات بنجاح")};
  const visible=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return tasks;return tasks.filter(x=>[x.id,x.serial_number,x.title,x.customer_name,x.employee_id,x.status].some(v=>String(v??"").toLowerCase().includes(q)))},[tasks,query]);
  const selectedTask=tasks.find(x=>String(x.id)===selected)??null; const selectedPhotos=photos.filter(p=>String(p.task_id)===selected); const selectedLocation=locations.find(i=>String(i.task_id)===selected)??null; const selectedCustomerPoint=selectedTask?parseCustomerLocation(selectedTask):null;
  const status=(s:string)=>({pending:"قيد الانتظار",accepted:"تم الاستلام",in_progress:"جاري التنفيذ",completed:"مكتمل"} as any)[s]??s;
  return <div className="space-y-6"><div className="panel p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="flex items-center gap-2 text-xl font-bold"><Truck className="size-5 text-primary"/>متابعة الأوردرات Live</h2><p className="mt-1 text-sm text-muted-foreground">حالات الأوردر والصور وموقع الموظف تتحدث لحظة بلحظة.</p></div><Button variant="outline" onClick={refresh} disabled={refreshing} className="gap-2"><RefreshCw className={`size-4 ${refreshing?"animate-spin":""}`}/><span>{refreshing?"جاري التحديث...":"تحديث"}</span></Button></div><div className="relative mt-4"><Search className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث برقم الأوردر أو العميل أو الموظف..." className="ps-9"/></div></div>
  <div className="grid gap-3 lg:grid-cols-2">{visible.map(task=>{const count=photos.filter(p=>String(p.task_id)===String(task.id)).length;const location=locations.find(i=>String(i.task_id)===String(task.id));const customerPoint=parseCustomerLocation(task);return <article key={String(task.id)} className="rounded-2xl border bg-card p-5 text-start transition hover:border-primary/50 hover:shadow-md"><button onClick={()=>setSelected(String(task.id))} className="w-full text-start"><div className="flex flex-wrap items-center gap-2"><b>{task.title||"أوردر"}</b><Badge>{status(String(task.status??""))}</Badge></div><p className="mt-2 text-sm">{task.customer_name||"—"}</p><div className="mt-3 grid gap-1 text-xs text-muted-foreground"><span>#{task.serial_number||task.id}</span><span><b>تاريخ ووقت الطلب الفعلي:</b> {formatActualDate(task.created_at)}</span><span><b>موعد الغسيل:</b> {task.scheduled_at ? formatActualDate(task.scheduled_at) : "—"}</span><span>{count} صورة • آخر تحديث {fmtDate(task.updated_at)}</span></div></button><div className="mt-4 flex flex-wrap items-center gap-2"><Button size="sm" variant="outline" onClick={()=>setSelected(String(task.id))}><MapPinned className="me-1 size-4"/>خريطة الموظف</Button>{location?<span className="text-xs text-emerald-600">الموظف متصل • آخر تحديث {new Date(location.updated_at).toLocaleTimeString()}</span>:<span className="text-xs text-muted-foreground">موقع الموظف غير متاح حالياً</span>}{customerPoint&&<span className="text-xs text-primary">موقع العميل مربوط</span>}</div></article>})}{visible.length===0&&<p className="text-sm text-muted-foreground">لا توجد أوردرات مطابقة.</p>}</div>
  <Dialog open={!!selectedTask} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="max-h-[92vh] max-w-5xl overflow-y-auto">{selectedTask&&<><DialogHeader><DialogTitle>{selectedTask.title||"تفاصيل الأوردر"}</DialogTitle><DialogDescription>خريطة مباشرة لموقع الموظف بالنسبة لموقع العميل، مع تحديثات لحظية.</DialogDescription></DialogHeader><div className="grid gap-3 rounded-xl border bg-muted/20 p-4 sm:grid-cols-3"><div><small className="text-muted-foreground">العميل</small><p className="font-semibold">{selectedTask.customer_name||"—"}</p></div><div><small className="text-muted-foreground">حالة الأوردر</small><p className="font-semibold">{status(String(selectedTask.status??""))}</p></div><div><small className="text-muted-foreground">رقم الأوردر</small><p className="font-semibold">#{selectedTask.serial_number||selectedTask.id}</p></div><div><small className="text-muted-foreground">تاريخ ووقت الطلب الفعلي</small><p className="font-semibold">{formatActualDate(selectedTask.created_at)}</p></div><div><small className="text-muted-foreground">موعد الغسيل</small><p className="font-semibold">{formatActualDate(selectedTask.scheduled_at)}</p></div><div><small className="text-muted-foreground">آخر تحديث</small><p className="font-semibold">{fmtDate(selectedTask.updated_at)}</p></div><div><small className="text-muted-foreground">الموظف</small><p className="font-semibold">{selectedTask.employee_id||"—"}</p></div></div><div className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="flex items-center gap-2 font-bold"><MapPinned className="size-5 text-primary"/>خريطة الموظف Live</h3>{selectedLocation&&<Badge variant="secondary">متصل الآن</Badge>}</div>{selectedCustomerPoint?<DeliveryMap destination={selectedCustomerPoint} driver={selectedLocation?{lat:Number(selectedLocation.latitude),lng:Number(selectedLocation.longitude),updatedAt:selectedLocation.updated_at}:null} height="420px"/>:<div className="rounded-2xl border p-8 text-center text-sm text-muted-foreground">لا يوجد موقع GPS أو إحداثيات قابلة للاستخراج من لينك موقع العميل في هذا الأوردر.</div>}{selectedTask.location_url&&<Button variant="outline" size="sm" onClick={()=>window.open(String(selectedTask.location_url),"_blank","noopener,noreferrer")}><MapPinned className="me-1 size-4"/>فتح موقع العميل في الخرائط</Button>}</div><div><h3 className="mb-3 flex items-center gap-2 font-bold"><Camera className="size-5 text-primary"/>صور الأوردر</h3><div className="grid gap-4 sm:grid-cols-2">{["before","after"].map(kind=><div key={kind}><h4 className="mb-2 font-semibold">{kind==="before"?"قبل الغسيل":"بعد التنظيف"}</h4><div className="grid gap-3">{selectedPhotos.filter(p=>p.kind===kind).map(p=><img key={p.id} src={p.url} alt={kind} className="w-full rounded-xl border object-cover"/>)}{selectedPhotos.filter(p=>p.kind===kind).length===0&&<p className="text-sm text-muted-foreground">لا توجد صور.</p>}</div></div>)}</div></div></>}</DialogContent></Dialog></div>;
}
