import { createFileRoute } from "@tanstack/react-router";
import { useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, XCircle } from "lucide-react";
import { toast } from "sonner";
import { CrudTable, type Row } from "@/components/admin/Crud";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { useI18n } from "@/lib/i18n";
import { useAdminTable } from "@/lib/data";

export const Route = createFileRoute("/_authenticated/admin/payments")({ component: AdminPayments });

function AdminPayments() {
  const { t, fmtMoney, fmtDate, pick } = useI18n();
  const queryClient = useQueryClient();
  const { data: customers } = useAdminTable("profiles", "id, full_name, phone", "created_at");
  const { data: subscriptions } = useAdminTable("subscriptions", "id, customer_id, package_id, status, start_date, end_date, total_washes, used_washes, request_id", "created_at");
  const { data: packages } = useAdminTable("packages", "id, title_en, title_ar", "sort_order");
  const { data: bookingRequests = [], refetch: refetchBookingRequests } = useAdminTable("booking_requests", "id, customer_name, customer_phone, customer_email, amount, payment_method, payment_status, status, scheduled_at, created_at", "created_at");
  const { data: subscriptionRequests = [], refetch: refetchSubscriptionRequests } = useAdminTable("subscription_requests", "id, customer_id, package_id, amount, payment_method, payment_status, status, requested_at, created_at, updated_at", "requested_at");
  const customerOptions = (customers ?? []).map((c) => ({ value: String(c.id), label: String(c.full_name ?? c.phone ?? c.id) }));
  const subscriptionOptions = (subscriptions ?? []).map((s) => ({ value: String(s.id), label: `${customerOptions.find((c) => c.value === String(s.customer_id))?.label ?? s.customer_id} — ${String(s.id).slice(0, 8)}` }));
  const packageLabel = (packageId: unknown) => { const p = (packages ?? []).find((x) => String(x.id) === String(packageId)); return p ? pick(String(p.title_en), String(p.title_ar)) : "—"; };
  const refresh = () => { queryClient.invalidateQueries({ queryKey: ["admin", "payments"] }); queryClient.invalidateQueries({ queryKey: ["admin", "subscriptions"] }); void refetchBookingRequests(); void refetchSubscriptionRequests(); };
  const manualPaymentMethod = (method: unknown) => { const value = String(method ?? ""); if (value === "smart_wallet") return pick("Smart Wallet", "محفظة"); if (value === "instapay") return "InstaPay"; if (value === "bank_transfer") return pick("Bank transfer", "تحويل بنكي"); if (value === "cash") return pick("Cash", "كاش"); return value || "—"; };
  const confirmManualPayment = async (request: Row) => { const id = String(request["id"] ?? ""); if (!id || String(request["payment_status"] ?? "") !== "awaiting_proof") return; if (!window.confirm(pick("Confirm this manual payment?", "تأكيد استلام الدفع اليدوي؟"))) return; const { error } = await (supabase as any).from("booking_requests").update({ payment_status: "paid" }).eq("id", id).eq("payment_status", "awaiting_proof"); if (error) return void toast.error(error.message); toast.success(pick("Payment confirmed", "تم تأكيد الدفع")); refresh(); };
  const rejectManualPayment = async (request: Row) => { const id = String(request["id"] ?? ""); if (!id || String(request["payment_status"] ?? "") !== "awaiting_proof") return; if (!window.confirm(pick("Reject this manual payment?", "رفض الدفع اليدوي؟"))) return; const { error } = await (supabase as any).from("booking_requests").update({ payment_status: "rejected" }).eq("id", id).eq("payment_status", "awaiting_proof"); if (error) return void toast.error(error.message); toast.success(pick("Payment rejected", "تم رفض الدفع")); refresh(); };
  const confirmSubscriptionPayment = async (row: any) => {
    const requestId = String(row["id"] ?? "");
    if (!requestId || String(row["status"] ?? "") !== "pending" || String(row["payment_status"] ?? "") !== "pending") return;
    if (!window.confirm("تأكيد الدفع وتفعيل الاشتراك؟ سيتم تنفيذ التفعيل يدويًا الآن من صفحة المدفوعات.")) return;
    const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return void toast.error("جلسة المدير غير موجودة.");
    const { data: request, error: requestReadError } = await (supabase as any).from("subscription_requests").select("*").eq("id", requestId).single(); if (requestReadError || !request) return void toast.error(requestReadError?.message ?? "طلب الاشتراك غير موجود.");
    const { data: payment, error: paymentReadError } = await (supabase as any).from("payments").select("id, status, subscription_id").eq("reference", `subscription_request:${requestId}`).order("created_at", { ascending: false }).limit(1).maybeSingle(); if (paymentReadError) return void toast.error(paymentReadError.message); if (!payment) return void toast.error("لم يتم إنشاء معاملة الدفع لهذا الاشتراك."); if (payment.status !== "pending") return void toast.error("حالة الدفع تغيرت بالفعل.");
    const now = new Date().toISOString();
    const { error: paymentError } = await (supabase as any).from("payments").update({ status: "paid", paid_at: now }).eq("id", payment.id).eq("status", "pending"); if (paymentError) return void toast.error(paymentError.message);
    const { error: requestPaidError } = await (supabase as any).from("subscription_requests").update({ payment_status: "paid", updated_at: now }).eq("id", requestId).eq("status", "pending");
    if (requestPaidError) { await (supabase as any).from("payments").update({ status: "pending", paid_at: null }).eq("id", payment.id); return void toast.error(requestPaidError.message); }
    const { data: subscriptionId, error: activationError } = await (supabase as any).rpc("confirm_subscription_request", { p_request_id: requestId, p_admin_id: auth.user.id });
    if (activationError) { await (supabase as any).from("payments").update({ status: "pending", paid_at: null }).eq("id", payment.id); await (supabase as any).from("subscription_requests").update({ payment_status: "pending", updated_at: new Date().toISOString() }).eq("id", requestId).eq("status", "pending"); return void toast.error(activationError.message); }
    const { error: linkError } = await (supabase as any).from("payments").update({ subscription_id: subscriptionId }).eq("id", payment.id); if (linkError) return void toast.error(linkError.message);
    toast.success("تم تأكيد الدفع وتفعيل الاشتراك يدويًا."); refresh();
  };
  return <div className="space-y-6">
    <section className="panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h2 className="text-lg font-bold">طلبات دفع الاشتراكات</h2><p className="text-sm text-muted-foreground">تظهر هنا قبل التفعيل. المدير هو الذي يؤكد الدفع ويقوم بالتفعيل يدويًا من هذه الصفحة.</p></div><Badge variant="secondary">{subscriptionRequests.filter((r: any) => r.status === "pending" && r.payment_status === "pending").length} معلقة</Badge></div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead><tr className="border-b bg-muted/40 text-right"><th className="p-3">العميل</th><th className="p-3">الباقة</th><th className="p-3">المبلغ</th><th className="p-3">طريقة الدفع</th><th className="p-3">تاريخ ووقت الطلب</th><th className="p-3">الحالة</th><th className="p-3">الإجراء</th></tr></thead><tbody>{subscriptionRequests.map((r: any) => { const pending = r.status === "pending" && r.payment_status === "pending"; return <tr key={`subscription-payment-${r.id}`} className="border-b last:border-0 hover:bg-muted/20"><td className="p-3"><div className="font-semibold">{customerOptions.find((c) => c.value === String(r.customer_id))?.label ?? r.customer_id}</div></td><td className="p-3">{packageLabel(r.package_id)}</td><td className="p-3 font-semibold">{fmtMoney(Number(r.amount ?? 0))}</td><td className="p-3">{manualPaymentMethod(r.payment_method)}</td><td className="p-3">{r.requested_at ? `${fmtDate(String(r.requested_at))} · ${new Date(String(r.requested_at)).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}` : "—"}</td><td className="p-3"><Badge variant={r.payment_status === "paid" ? "default" : r.status === "cancelled" ? "destructive" : "secondary"}>{r.payment_status === "paid" ? "مدفوع" : r.status === "pending" ? "في انتظار التأكيد" : r.status}</Badge></td><td className="p-3">{pending ? <Button size="sm" onClick={() => void confirmSubscriptionPayment(r)}><CheckCircle2 className="me-1 size-4"/>تأكيد الدفع وتفعيل الاشتراك</Button> : <span className="text-xs text-muted-foreground">—</span>}</td></tr>; })}{subscriptionRequests.length === 0 && <tr><td colSpan={7} className="p-8 text-center text-muted-foreground">لا توجد طلبات اشتراك.</td></tr>}</tbody></table></div></section>
    <section className="panel overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h2 className="text-lg font-bold">طلبات الدفع اليدوي</h2><p className="text-sm text-muted-foreground">المحفظة وInstaPay والتحويل البنكي — تظهر هنا فور إرسال العميل للدفع وتنتظر تأكيد المدير.</p></div><Badge variant="secondary">{bookingRequests.filter((r: any) => r.payment_status === "awaiting_proof").length} معلقة</Badge></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b bg-muted/40 text-right"><th className="p-3">العميل</th><th className="p-3">المبلغ</th><th className="p-3">طريقة الدفع</th><th className="p-3">تاريخ ووقت الطلب</th><th className="p-3">حالة الدفع</th><th className="p-3">حالة الطلب</th><th className="p-3">الإجراء</th></tr></thead><tbody>{bookingRequests.filter((r: any) => ["awaiting_proof", "paid", "rejected"].includes(String(r.payment_status))).map((r: any) => <tr key={`booking-payment-${r.id}`} className="border-b last:border-0 hover:bg-muted/20"><td className="p-3"><div className="font-semibold">{r.customer_name || "—"}</div><div className="text-xs text-muted-foreground">{r.customer_phone || r.customer_email || "—"}</div></td><td className="p-3 font-semibold">{fmtMoney(Number(r.amount ?? 0))}</td><td className="p-3">{manualPaymentMethod(r.payment_method)}</td><td className="p-3">{r.created_at ? `${fmtDate(String(r.created_at))} · ${new Date(String(r.created_at)).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}` : "—"}</td><td className="p-3"><Badge variant={r.payment_status === "paid" ? "default" : r.payment_status === "rejected" ? "destructive" : "secondary"}>{r.payment_status === "awaiting_proof" ? "في انتظار التأكيد" : r.payment_status === "paid" ? "مدفوع" : "مرفوض"}</Badge></td><td className="p-3"><Badge variant="outline">{r.status || "—"}</Badge></td><td className="p-3">{r.payment_status === "awaiting_proof" ? <div className="flex gap-2"><Button size="sm" onClick={() => confirmManualPayment(r)}><CheckCircle2 className="me-1 size-4"/>تأكيد</Button><Button size="sm" variant="destructive" onClick={() => rejectManualPayment(r)}><XCircle className="me-1 size-4"/>رفض</Button></div> : <span className="text-xs text-muted-foreground">—</span>}</td></tr>)}{bookingRequests.filter((r: any) => ["awaiting_proof", "paid", "rejected"].includes(String(r.payment_status))).length === 0 && <tr><td colSpan={7} className="p-8 text-center text-muted-foreground">لا توجد طلبات دفع يدوية.</td></tr>}</tbody></table></div></section>
    <CrudTable table="payments" title={t("a_payments")} orderBy="created_at" columns={[{key:"customer_id",label:t("customer"),render:(r)=>customerOptions.find((c)=>c.value===String(r["customer_id"]))?.label??"—"},{key:"subscription_id",label:"الاشتراك",render:(r)=>subscriptionOptions.find((s)=>s.value===String(r["subscription_id"]))?.label??"غير مرتبط"},{key:"amount",label:t("amount"),render:(r)=>fmtMoney(Number(r["amount"]??0))},{key:"method",label:t("method")},{key:"reference",label:t("reference")},{key:"created_at",label:"تاريخ ووقت الطلب",render:(r)=>r["created_at"]?`${fmtDate(String(r["created_at"]))} · ${new Date(String(r["created_at"])).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`:"—"},{key:"paid_at",label:t("paid_at"),render:(r)=>r["paid_at"]?`${fmtDate(String(r["paid_at"]))} · ${new Date(String(r["paid_at"])).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}`:"—"},{key:"status",label:t("status"),render:(r)=><Badge variant={String(r["status"])==="paid"?"default":"secondary"}>{String(r["status"])==="paid"?"مدفوع":String(r["status"]??"pending")}</Badge>}]}
      fields={[{name:"customer_id",label:t("customer"),type:"select",options:customerOptions},{name:"subscription_id",label:"الاشتراك",type:"select",options:subscriptionOptions},{name:"amount",label:t("amount"),type:"number",defaultValue:0},{name:"method",label:t("method"),type:"select",defaultValue:"cash",options:[{value:"cash",label:"Cash"},{value:"instapay",label:"InstaPay"},{value:"vodafone_cash",label:"Vodafone Cash"},{value:"card",label:t("card")}]},{name:"reference",label:t("reference")},{name:"paid_at",label:t("paid_at"),type:"date"},{name:"status",label:t("status"),type:"select",defaultValue:"pending",options:[{value:"paid",label:"مدفوع"},{value:"pending",label:t("pending")},{value:"cancelled",label:t("cancelled")}] }]} rowActions={(row)=>String(row["status"]??"")==="pending"&&row["subscription_id"]?<Button variant="outline" size="sm" onClick={()=>void confirmSubscriptionPayment(row)}><CheckCircle2 className="me-1 size-4"/>تأكيد الدفع وتفعيل الاشتراك</Button>:null}/>
  </div>;
}