import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { CheckCircle2, ClipboardList, ExternalLink, MapPin, Navigation, Plus, Trash2, CarFront } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import { useI18n } from "@/lib/i18n";
import { useAdminTable } from "@/lib/data";

export const Route = createFileRoute("/_authenticated/admin/tasks")({ component: AdminTasks });

type FormState={employee_id:string;customer_id:string;car_id:string;subscription_id:string;offer_id:string;package_id:string;title:string;wash_type:string;collection_amount:string;location_text:string;location_url:string;latitude:string;longitude:string;scheduled_at:string;notes:string};
const emptyForm:FormState={employee_id:"",customer_id:"",car_id:"",subscription_id:"",offer_id:"",package_id:"",title:"",wash_type:"car_wash",collection_amount:"",location_text:"",location_url:"",latitude:"",longitude:"",scheduled_at:"",notes:""};

function AdminTasks(){
 const {pick}=useI18n();
 const {data:profiles=[]}=useAdminTable("profiles","*","created_at");
 const {data:customers=[]}=useAdminTable("customers","*","created_at");
 const {data:cars=[]}=useAdminTable("cars","*","created_at");
 const {data:subscriptions=[],refetch:refetchSubs}=useAdminTable("subscriptions","*, packages(title_en,title_ar,washes_count,duration_days)","created_at");
 const {data:packages=[]}=useAdminTable("packages","id,title_en,title_ar,washes_count,duration_days,price,status","sort_order");
 const {data:offers=[]}=useAdminTable("offers","*","created_at");
 const {data:tasks=[],refetch}=useAdminTable("employee_tasks","*","created_at");
 const [form,setForm]=useState<FormState>(emptyForm);
 const employees=profiles.filter((p:any)=>p.role==="employee"&&p.status!=="suspended");
 const customerLabel=(c:any)=>c?.full_name||c?.name||c?.email||c?.phone||c?.id;
 const employeeLabel=(e:any)=>e?.full_name||e?.name||e?.email||e?.id;
 const carLabel=(c:any)=>[c?.brand,c?.model,c?.color,c?.plate_number].filter(Boolean).join(" · ")||c?.id;
 const set=(key:keyof FormState,value:string)=>setForm(f=>({...f,[key]:value}));
 const selectedSub=subscriptions.find((s:any)=>s.id===form.subscription_id);
 const selectedCustomer=customers.find((c:any)=>c.id===form.customer_id);
 const selectedCar=cars.find((c:any)=>c.id===form.car_id);
 const selectedPackage=packages.find((p:any)=>p.id===form.package_id);
 const customerCars=cars.filter((c:any)=>c.customer_id===form.customer_id);
 const activeSubs=subscriptions.filter((s:any)=>s.status==="active"&&(!form.customer_id||s.customer_id===form.customer_id)&&new Date(`${s.end_date}T23:59:59`).getTime()>=Date.now());
 const useMyLocation=()=>{if(!navigator.geolocation){toast.error(pick("Location is not supported by this browser","المتصفح لا يدعم تحديد الموقع"));return;}navigator.geolocation.getCurrentPosition(p=>{const latitude=String(p.coords.latitude),longitude=String(p.coords.longitude);setForm(f=>({...f,latitude,longitude,location_url:`https://www.google.com/maps/search/?api=1&query=${latitude},${longitude}`}));},()=>toast.error(pick("Could not get your location","تعذر الحصول على موقعك")));};
 const createTask=async()=>{
  if(!form.employee_id||!form.customer_id||!form.title||(!form.location_text&&!form.location_url&&!(form.latitude&&form.longitude))){toast.error(pick("Fill employee, customer, task and a location","اكمل الموظف والعميل والمهمة والموقع"));return;}
  const sub=selectedSub;const offer=offers.find((o:any)=>o.id===form.offer_id);const pkg=(sub?.packages as any)||selectedPackage;const {data:auth}=await supabase.auth.getUser();if(!auth.user)return;
  const locationUrl=form.location_url||(form.latitude&&form.longitude?`https://www.google.com/maps/search/?api=1&query=${form.latitude},${form.longitude}`:null);
  const {error}=await(supabase as any).from("employee_tasks").insert({serial_number:`TW-${Date.now().toString(36).toUpperCase()}`,collection_amount:form.collection_amount?Number(form.collection_amount):0,title:form.title,wash_type:form.wash_type,employee_id:form.employee_id,customer_id:form.customer_id,car_id:form.car_id||sub?.car_id||null,subscription_id:form.subscription_id||null,offer_id:form.offer_id||null,package_id:form.package_id||sub?.package_id||null,customer_name:customerLabel(selectedCustomer),customer_phone:selectedCustomer?.phone??null,customer_email:selectedCustomer?.email??null,package_name:pkg?pick(pkg.title_en??"",pkg.title_ar??""):null,offer_name:offer?pick(offer.title_en??"",offer.title_ar??""):null,total_washes:sub?.total_washes??pkg?.washes_count??null,used_washes:sub?.used_washes??0,remaining_washes:sub?Math.max(Number(sub.total_washes??0)-Number(sub.used_washes??0),0):pkg?.washes_count??null,location_text:form.location_text||locationUrl,location_url:locationUrl,latitude:form.latitude?Number(form.latitude):null,longitude:form.longitude?Number(form.longitude):null,scheduled_at:form.scheduled_at||null,notes:form.notes||null,status:"pending",created_by:auth.user.id});
  if(error){toast.error(error.message);return;}toast.success(pick("Task assigned","تم تكليف الموظف بالمهمة"));setForm(emptyForm);refetch();refetchSubs();
 };
 const updateStatus=async(id:string,status:string)=>{const {error}=await(supabase as any).from("employee_tasks").update({status,...(status==="completed"?{completed_at:new Date().toISOString()}: {})}).eq("id",id);if(error)toast.error(error.message);else refetch();};
 const removeTask=async(id:string)=>{const {error}=await(supabase as any).from("employee_tasks").delete().eq("id",id);if(error)toast.error(error.message);else refetch();};
 const openLocation=(task:any)=>{const url=task.location_url||(task.latitude!=null&&task.longitude!=null?`https://www.google.com/maps/search/?api=1&query=${task.latitude},${task.longitude}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(task.location_text||"")}`);window.open(url,"_blank","noopener,noreferrer");};
 return <div className="space-y-6">
  <div className="flex items-center gap-3"><ClipboardList className="size-6 text-primary"/><div><h1 className="text-2xl font-bold">{pick("Employee tasks & orders","مهام وأوردرات الموظفين")}</h1><p className="text-sm text-muted-foreground">{pick("Assign washes with customer, car, package and location details.","كلف الموظف بالغسيل مع بيانات العميل والعربية والباقة والموقع بالتفصيل.")}</p></div></div>
  <section className="panel p-6"><div className="grid gap-4 md:grid-cols-2">
   <div><Label>{pick("Employee","الموظف")}</Label><select className="mt-2 h-10 w-full rounded-md border bg-background px-3" value={form.employee_id} onChange={e=>set("employee_id",e.target.value)}><option value="">{pick("Choose employee","اختر الموظف")}</option>{employees.map((e:any)=><option key={e.id} value={e.id}>{employeeLabel(e)}</option>)}</select></div>
   <div><Label>{pick("Customer","العميل")}</Label><select className="mt-2 h-10 w-full rounded-md border bg-background px-3" value={form.customer_id} onChange={e=>setForm(f=>({...f,customer_id:e.target.value,car_id:"",subscription_id:"",package_id:"",offer_id:""}))}><option value="">{pick("Choose customer","اختر العميل")}</option>{customers.map((c:any)=><option key={c.id} value={c.id}>{customerLabel(c)}</option>)}</select></div>
   <div><Label>{pick("Customer car","عربية العميل")}</Label><select className="mt-2 h-10 w-full rounded-md border bg-background px-3" value={form.car_id} onChange={e=>set("car_id",e.target.value)} disabled={!form.customer_id}><option value="">{pick("Choose car","اختر العربية")}</option>{customerCars.map((c:any)=><option key={c.id} value={c.id}>{carLabel(c)}</option>)}</select></div>
   <div><Label>{pick("Active customer subscription","اشتراك العميل النشط")}</Label><select className="mt-2 h-10 w-full rounded-md border bg-background px-3" value={form.subscription_id} onChange={e=>{const id=e.target.value;const s=subscriptions.find((x:any)=>x.id===id);setForm(f=>({...f,subscription_id:id,package_id:s?.package_id||"",car_id:f.car_id||s?.car_id||""}));}}><option value="">{pick("No subscription","بدون اشتراك")}</option>{activeSubs.map((s:any)=>{const p=s.packages as any;return <option key={s.id} value={s.id}>{p?pick(p.title_en,p.title_ar):pick("Package","باقة")} — {s.used_washes??0}/{s.total_washes??0}</option>})}</select></div>
   <div><Label>{pick("Package type / available packages","نوع الباقة / الباقات المتاحة")}</Label><select className="mt-2 h-10 w-full rounded-md border bg-background px-3" value={form.package_id} onChange={e=>{const p=packages.find((x:any)=>x.id===e.target.value);const s=activeSubs.find((x:any)=>x.package_id===e.target.value);setForm(f=>({...f,package_id:e.target.value,subscription_id:s?.id||f.subscription_id,car_id:f.car_id||s?.car_id||""}));if(p&&!s&&form.customer_id)toast.info(pick("This package is available, but the customer has no active subscription for it.","الباقة متاحة، لكن العميل لا يملك اشتراكًا نشطًا بها."));}}><option value="">{pick("Choose available package","اختر الباقة المتاحة")}</option>{packages.filter((p:any)=>p.status==="active").map((p:any)=><option key={p.id} value={p.id}>{pick(p.title_en,p.title_ar)} — {p.washes_count} {pick("washes","غسلات")} · {p.price} EGP</option>)}</select></div>
   <div><Label>{pick("Task / wash","المهمة / الغسيل")}</Label><Input className="mt-2" value={form.title} onChange={e=>set("title",e.target.value)}/></div>
   <div><Label>{pick("Wash type","نوع الغسيل")}</Label><select className="mt-2 h-10 w-full rounded-md border bg-background px-3" value={form.wash_type} onChange={e=>set("wash_type",e.target.value)}><option value="car_wash">{pick("Car wash","غسيل سيارة")}</option><option value="interior">{pick("Interior","داخلي")}</option><option value="exterior">{pick("Exterior","خارجي")}</option><option value="full">{pick("Full","كامل")}</option></select></div>
   <div><Label>{pick("Collection amount","مبلغ التحصيل")}</Label><Input className="mt-2" type="number" min="0" step="0.01" value={form.collection_amount} onChange={e=>set("collection_amount",e.target.value)}/></div>
   <div><Label>{pick("Scheduled time","موعد التنفيذ")}</Label><Input className="mt-2" type="datetime-local" value={form.scheduled_at} onChange={e=>set("scheduled_at",e.target.value)}/></div>
   <div className="md:col-span-2"><Label>{pick("Location address","عنوان الموقع")}</Label><Input className="mt-2" value={form.location_text} onChange={e=>set("location_text",e.target.value)}/></div>
   <div className="md:col-span-2"><Label>{pick("Google Maps / location link","لينك الموقع أو Google Maps")}</Label><div className="mt-2 flex gap-2"><Input value={form.location_url} onChange={e=>set("location_url",e.target.value)}/>{form.location_url&&<Button type="button" variant="outline" size="icon" onClick={()=>window.open(form.location_url,"_blank","noopener,noreferrer")}><ExternalLink className="size-4"/></Button>}</div></div>
   <div><Label>{pick("Latitude","خط العرض")}</Label><Input className="mt-2" value={form.latitude} onChange={e=>set("latitude",e.target.value)}/></div><div><Label>{pick("Longitude","خط الطول")}</Label><Input className="mt-2" value={form.longitude} onChange={e=>set("longitude",e.target.value)}/></div>
   <div className="md:col-span-2 flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={useMyLocation}><Navigation className="me-1 size-4"/>{pick("Use my current location","استخدام موقعي الحالي")}</Button>{form.latitude&&form.longitude&&<Button type="button" variant="outline" onClick={()=>window.open(`https://www.google.com/maps/search/?api=1&query=${form.latitude},${form.longitude}`,"_blank","noopener,noreferrer")}><MapPin className="me-1 size-4"/>{pick("Open on map","فتح على الخريطة")}</Button>}</div>
   <div className="md:col-span-2"><Label>{pick("Instructions / notes","تعليمات وملاحظات")}</Label><Textarea className="mt-2" value={form.notes} onChange={e=>set("notes",e.target.value)}/></div>
  </div><Button className="mt-5" onClick={createTask}><Plus className="me-2 size-4"/>{pick("Assign task","تكليف الموظف")}</Button></section>
  <section className="panel p-6"><h2 className="text-lg font-bold">{pick("Assigned orders","الأوردرات المكلفة")}</h2><div className="mt-4 space-y-3">{tasks.map((task:any)=>{const emp=profiles.find((p:any)=>p.id===task.employee_id);const car=cars.find((c:any)=>c.id===task.car_id);return <div key={task.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{task.title} <span className="text-xs text-muted-foreground">#{task.serial_number||String(task.id).slice(0,8).toUpperCase()}</span></p><p className="text-sm text-muted-foreground">{emp?.full_name||emp?.email} · {task.customer_name||"—"} · {task.customer_phone||"—"}</p>{car&&<p className="mt-1 flex items-center gap-1 text-sm"><CarFront className="size-4"/>{carLabel(car)}</p>}<p className="mt-1 text-sm">{pick("Package type","نوع الباقة")}: <b>{task.package_name||task.offer_name||"—"}</b></p><p className="mt-1 text-sm">{pick("Remaining washes","الغسلات المتبقية")}: <b>{task.remaining_washes??"—"}</b></p><p className="mt-1 flex items-center gap-1 text-sm"><MapPin className="size-4"/>{task.location_text||task.location_url||"—"}</p><p className="mt-1 text-sm font-semibold">{pick("Collection","التحصيل")}: {Number(task.collection_amount??0).toFixed(2)} EGP</p></div><Badge>{task.status||"pending"}</Badge></div><div className="mt-3 flex flex-wrap gap-2">{(task.location_url||task.latitude!=null||task.longitude!=null||task.location_text)&&<Button size="sm" variant="outline" onClick={()=>openLocation(task)}><Navigation className="me-1 size-4"/>{pick("Open location","فتح الموقع")}</Button>}{task.status!=="completed"&&<Button size="sm" onClick={()=>void updateStatus(task.id,"completed")}><CheckCircle2 className="me-1 size-4"/>{pick("Complete","تم التنفيذ")}</Button>}<Button size="sm" variant="ghost" onClick={()=>void removeTask(task.id)}><Trash2 className="me-1 size-4"/>{pick("Delete","حذف")}</Button></div></div>})}{!tasks.length&&<p className="text-sm text-muted-foreground">{pick("No assigned tasks yet.","لا توجد مهام مكلفة حالياً.")}</p>}</div></section>
 </div>;
}
