import { Check, Sparkles, Tag } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useI18n } from "@/lib/i18n";

type Pkg={id:string;image_url:string|null;title_en:string;title_ar:string;description_en:string|null;description_ar:string|null;features_en:string[];features_ar:string[];price:number;duration_days:number;washes_count:number};
export function PackageCard({pkg,featured}:{pkg:Pkg;featured?:boolean}){const{t,pick,fmtMoney}=useI18n();const features=pick(pkg.features_en,pkg.features_ar)??[];return <article className={featured?"surface-ink animate-fade-up relative flex flex-col overflow-hidden rounded-3xl p-7 shadow-luxe":"panel animate-fade-up relative flex flex-col overflow-hidden p-7 transition-transform duration-300 hover:-translate-y-1"}>{featured&&<Badge className="mb-4 w-fit bg-primary text-primary-foreground"><Sparkles className="me-1 size-3"/>{pick("Most popular","الأكثر طلباً")}</Badge>}{pkg.image_url&&<img src={pkg.image_url} alt={pick(pkg.title_en,pkg.title_ar)} loading="lazy" className="mb-5 h-36 w-full rounded-2xl object-cover"/>}<h3 className="text-2xl font-bold">{pick(pkg.title_en,pkg.title_ar)}</h3><p className={featured?"mt-2 text-sm text-ink-foreground/70":"mt-2 text-sm text-muted-foreground"}>{pick(pkg.description_en,pkg.description_ar)}</p><div className="mt-6 flex items-end gap-2"><span className="font-display text-4xl font-extrabold">{fmtMoney(pkg.price)}</span><span className={featured?"pb-1 text-sm text-ink-foreground/60":"pb-1 text-sm text-muted-foreground"}>{t("currency_month")}</span></div><p className={featured?"mt-1 text-xs uppercase tracking-widest text-ink-foreground/50":"mt-1 text-xs uppercase tracking-widest text-muted-foreground"}>{pkg.washes_count} {pick("washes","غسلة")} · {pkg.duration_days} {pick("days","يوم")}</p><ul className="mt-6 space-y-2.5 text-sm">{features.map(f=><li key={f} className="flex items-start gap-2"><Check className="mt-0.5 size-4 shrink-0 text-primary"/><span>{f}</span></li>)}</ul><Button asChild className="mt-7 w-full" variant={featured?"secondary":"default"}><Link to="/book" search={{type:"package",id:pkg.id}}>{pick("View details & book","التفاصيل وحجز الموعد")}</Link></Button></article>}

type Offer={id:string;image_url:string|null;title_en:string;title_ar:string;description_en:string|null;description_ar:string|null;old_price:number|null;new_price:number|null;end_date:string|null};
export function OfferCard({offer}:{offer:Offer}){const{pick,fmtMoney,fmtDate}=useI18n();return <article className="panel animate-fade-up flex flex-col overflow-hidden transition-transform duration-300 hover:-translate-y-1">{offer.image_url?<img src={offer.image_url} alt={pick(offer.title_en,offer.title_ar)} loading="lazy" className="h-40 w-full object-cover"/>:<div className="surface-blue flex h-40 items-center justify-center"><Tag className="size-10 opacity-80"/></div>}<div className="flex flex-1 flex-col p-6"><h3 className="text-xl font-bold">{pick(offer.title_en,offer.title_ar)}</h3><p className="mt-2 flex-1 text-sm text-muted-foreground">{pick(offer.description_en,offer.description_ar)}</p><div className="mt-5 flex items-center gap-3">{offer.old_price!=null&&<span className="text-sm text-muted-foreground line-through">{fmtMoney(offer.old_price)}</span>}{offer.new_price!=null&&<span className="font-display text-2xl font-bold text-primary">{fmtMoney(offer.new_price)}</span>}</div>{offer.end_date&&<p className="mt-3 text-xs text-muted-foreground">{pick("Ends","ينتهي")} {fmtDate(offer.end_date)}</p>}<Button asChild className="mt-5"><Link to="/book" search={{type:"offer",id:offer.id}}>{pick("View details & book","التفاصيل وحجز الموعد")}</Link></Button></div></article>}
