import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { CarFront, CreditCard, Droplets, MessageCircle, Phone, RefreshCw, ShieldCheck, Tag, BriefcaseBusiness } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { AppTopbar, StatCard } from "@/components/app/Shell";
import { ProfileEditor } from "@/components/app/ProfileEditor";
import { supabase } from "@/integrations/supabase/client";
import { useI18n } from "@/lib/i18n";
import { useSession, useUserRoles } from "@/lib/auth";
import { useMyCards, useMySubscription, useMyWashes, useOffers, usePackages, useProfile, useSettings } from "@/lib/data";

export const Route = createFileRoute("/_authenticated/dashboard")({ component: CustomerDashboard });
type CurrentOrder = Record<string, any>;
type EmployeeInfo = { employee_id: string | null; national_id: string | null; card_number: string | null; job_title: string | null; branch: string | null; full_name: string | null };

const orderStages = [
  { key: "pending", en: "Your order has been received", ar: "تم استلام طلبك", icon: "📥" },
  { key: "confirmed", en: "Your order has been confirmed", ar: "تم تأكيد طلبك", icon: "✅" },
  { key: "on_the_way", en: "TapWash is on the way", ar: "تاب وش في الطريق", icon: "🚗" },
  { key: "arrived", en: "TapWash has arrived", ar: "تم وصول تاب وش", icon: "📍" },
  { key: "in_progress", en: "Service has started", ar: "بدء التنفيذ", icon: "✨" },
  { key: "completed", en: "Your order is complete", ar: "تم انهاء طلبك", icon: "🏁" },
];
function normalizeOrderStatus(status: string | null | undefined) {
  const value = String(status ?? "pending").toLowerCase();
  if (["new", "created", "pending", "requested"].includes(value)) return "pending";
  if (["approved", "confirmed", "accepted", "assigned"].includes(value)) return "confirmed";
  if (["on_the_way", "on-the-way", "out_for_delivery"].includes(value)) return "on_the_way";
  if (["arrived", "delivered", "picked_up", "picked-up", "pickup", "collected", "courier_picked_up"].includes(value)) return "arrived";
  if (["in_progress", "in-progress", "washing", "processing", "started"].includes(value)) return "in_progress";
  if (["completed", "complete", "finished", "closed"].includes(value)) return "completed";
  return "pending";
}

function CustomerDashboard() {
  const { t, pick, fmtDate, lang, setLang } = useI18n();
  const { user } = useSession();
  const { data: profile } = useProfile(user?.id); const { data: sub } = useMySubscription(user?.id); const { data: washes } = useMyWashes(user?.id); const { data: cards } = useMyCards(user?.id); const { data: roles } = useUserRoles(user?.id); const { data: packages } = usePackages(); const { data: offers } = useOffers(); const { data: settings } = useSettings();
  const [currentOrder, setCurrentOrder] = useState<CurrentOrder | null>(null); const [employeeInfo, setEmployeeInfo] = useState<EmployeeInfo | null>(null);
  useEffect(() => { if (profile?.language && (profile.language === "ar" || profile.language === "en") && profile.language !== lang) setLang(profile.language); }, [profile?.language]);
  const total = sub?.total_washes ?? 0; const used = sub?.used_washes ?? 0; const remaining = Math.max(total - used, 0); const lastWash = washes?.[0]?.washed_at ?? null; const wa = (settings?.whatsapp ?? "").replace(/[^\d]/g, "");
  const isAdmin = (roles ?? []).includes("admin"); const isEmployee = !isAdmin && (roles ?? []).includes("employee"); const activePackages = (packages ?? []).filter(p => p.status === "active"); const activeOffers = (offers ?? []).filter(o => o.status === "active"); const money = (value: number | string) => `${Number(value).toLocaleString(lang === "ar" ? "ar-EG" : "en-US")} ${t("egp")}`;

  useEffect(() => {
    if (!user?.id) return; let mounted = true;
    const loadOrder = async () => {
      const { data } = await (supabase as any).from("booking_requests").select("*").eq("customer_id", user.id).not("status", "in", "(completed,closed,rejected)").order("updated_at", { ascending: false }).limit(1).maybeSingle();
      if (mounted) setCurrentOrder(data ?? null);
    };
    void loadOrder();
    const channel = supabase.channel(`customer-booking-order-${user.id}`).on("postgres_changes", { event: "*", schema: "public", table: "booking_requests", filter: `customer_id=eq.${user.id}` }, () => void loadOrder()).subscribe();
    return () => { mounted = false; void supabase.removeChannel(channel); };
  }, [user?.id]);

  useEffect(() => {
    if (!isEmployee || !user?.email) return; let mounted = true;
    const loadEmployee = async () => { const { data } = await (supabase as any).from("employees").select("employee_id,national_id,card_number,job_title,branch,full_name").eq("email", user.email).maybeSingle(); if (mounted) setEmployeeInfo(data ?? null); };
    void loadEmployee(); return () => { mounted = false; };
  }, [isEmployee, user?.email]);

  const renew = () => { const text = pick(`Hello TapWash, I would like to renew my subscription. Name: ${profile?.full_name ?? ""}`, `مرحباً تاب واش، أرغب في تجديد اشتراكي. الاسم: ${profile?.full_name ?? ""}`); if (wa) window.open(`https://wa.me/${wa}?text=${encodeURIComponent(text)}`, "_blank"); toast.success(t("renew_requested")); };
  const statusLabel = (s?: string | null) => s === "active" ? t("active") : s === "expired" ? t("expired") : s === "cancelled" ? t("cancelled") : s === "pending" ? t("pending") : t("none");

  return <div className="customer-dashboard min-h-screen bg-background"><AppTopbar title={t("my_membership")} extra={isAdmin ? <Button asChild variant="outline" size="sm" className="hidden sm:inline-flex"><Link to="/admin"><ShieldCheck className="me-1.5 size-4" />{t("nav_admin")}</Link></Button> : null} /><div className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-6">
    <div className="panel animate-fade-up flex flex-wrap items-center gap-5 p-6">{profile?.avatar_url ? <img src={profile.avatar_url} alt={profile.full_name || "avatar"} className="size-16 rounded-2xl object-cover" /> : <div className="surface-blue flex size-16 items-center justify-center rounded-2xl font-display text-xl font-bold shadow-luxe">{(profile?.full_name || user?.email || "T").slice(0, 1).toUpperCase()}</div>}<div className="min-w-0"><p className="text-xs uppercase tracking-widest text-muted-foreground">{t("welcome_back")}</p><h2 className="truncate text-2xl font-bold">{profile?.full_name || user?.email}</h2><div className="mt-1 flex flex-wrap items-center gap-2 text-sm text-muted-foreground"><Badge variant={profile?.status === "active" ? "default" : "destructive"}>{profile?.status === "active" ? t("active") : t("suspended")}</Badge>{isEmployee && <Badge variant="secondary">{pick("Employee", "موظف")}</Badge>}{isAdmin && <Badge variant="secondary">{pick("Admin", "مدير")}</Badge>}{profile?.phone && <span>{profile.phone}</span>}</div></div><div className="ms-auto flex flex-wrap gap-2"><ProfileEditor /></div></div>

    {isEmployee && employeeInfo ? <section className="panel mt-6 p-6"><div className="mb-4 flex items-center gap-2"><BriefcaseBusiness className="size-5 text-primary" /><div><h3 className="text-lg font-bold">{pick("Employee information", "بيانات الموظف")}</h3><p className="text-sm text-muted-foreground">{pick("These fields are managed by management and are read-only for employees.", "هذه البيانات يتم تعديلها من المدير فقط ولا يمكن للموظف تعديلها.")}</p></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl border p-4"><span className="text-xs text-muted-foreground">{pick("Job title", "المسمى الوظيفي")}</span><p className="mt-1 font-semibold">{employeeInfo.job_title || "—"}</p></div><div className="rounded-xl border p-4"><span className="text-xs text-muted-foreground">{pick("Employee ID", "رقم ID الموظف")}</span><p className="mt-1 font-semibold">{employeeInfo.employee_id || "—"}</p></div><div className="rounded-xl border p-4"><span className="text-xs text-muted-foreground">{pick("Card number", "رقم البطاقة")}</span><p className="mt-1 font-semibold">{employeeInfo.card_number || "—"}</p></div><div className="rounded-xl border p-4"><span className="text-xs text-muted-foreground">{pick("National ID", "الرقم القومي")}</span><p className="mt-1 font-semibold">{employeeInfo.national_id || "—"}</p></div></div></section> : null}

    {currentOrder ? <section className="panel mt-6 overflow-hidden p-0"><div className="border-b bg-primary/5 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-muted-foreground">{pick("Current order", "الطلب الحالي")}</p><h3 className="mt-1 text-xl font-bold">{currentOrder.title || pick("Car wash order", "طلب غسيل سيارة")}</h3></div><Badge className="px-3 py-1">{pick((orderStages.find(s => s.key === normalizeOrderStatus(currentOrder.status)) ?? orderStages[0]).en, (orderStages.find(s => s.key === normalizeOrderStatus(currentOrder.status)) ?? orderStages[0]).ar)}</Badge></div></div>
      <div className="p-6"><div className="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><span className="text-xs text-muted-foreground">{pick("Order number", "رقم الطلب")}</span><p className="mt-1 font-semibold">{currentOrder.serial_number ? `#${currentOrder.serial_number}` : String(currentOrder.id).slice(0, 8)}</p></div><div><span className="text-xs text-muted-foreground">{pick("Scheduled", "الموعد")}</span><p className="mt-1 font-semibold">{currentOrder.scheduled_at ? fmtDate(currentOrder.scheduled_at) : "—"}</p></div><div><span className="text-xs text-muted-foreground">{pick("Payment", "الدفع")}</span><p className="mt-1 font-semibold">{currentOrder.payment_status || "—"}</p></div><div><span className="text-xs text-muted-foreground">{pick("Last update", "آخر تحديث")}</span><p className="mt-1 font-semibold">{currentOrder.updated_at ? fmtDate(currentOrder.updated_at) : "—"}</p></div></div>
      <div className="space-y-3">{orderStages.map((stage, i) => { const currentIndex = Math.max(orderStages.findIndex(s => s.key === normalizeOrderStatus(currentOrder.status)), 0); const done = i <= currentIndex; const active = i === currentIndex; return <div key={stage.key} className="flex items-center gap-3"><div className={`flex size-9 shrink-0 items-center justify-center rounded-full border ${done ? "border-primary bg-primary text-primary-foreground" : "border-border bg-background text-muted-foreground"}`}>{stage.icon}</div><div className={`flex-1 rounded-xl px-3 py-2 ${active ? "bg-primary/10 font-bold" : done ? "text-foreground" : "text-muted-foreground"}`}><p>{pick(stage.en, stage.ar)}</p>{active && <p className="mt-0.5 text-xs font-normal text-primary">{pick("Current status", "الحالة الحالية")}</p>}</div></div>; })}</div></div></section> : null}

    {sub ? <><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard tone="ink" label={t("package")} value={sub.packages ? pick(sub.packages.title_en, sub.packages.title_ar) : t("none")} hint={`${total} ${pick("washes", "غسلة")}`} /><StatCard tone="primary" label={t("remaining_washes")} value={remaining} hint={`${used} ${pick("used", "مستخدمة")}`} /><StatCard label={t("subscription_status")} value={statusLabel(sub.status)} /><StatCard label={t("last_wash")} value={fmtDate(lastWash)} /></div><div className="panel mt-6 p-6"><div className="flex items-center justify-between text-sm"><span className="font-semibold">{t("used_washes")}</span><span className="text-muted-foreground">{used} / {total}</span></div><Progress value={total ? used / total * 100 : 0} className="mt-3" /><div className="mt-6 grid gap-4 sm:grid-cols-2"><div><p className="text-xs uppercase tracking-widest text-muted-foreground">{t("start_date")}</p><p className="mt-1 font-semibold">{fmtDate(sub.start_date)}</p></div><div><p className="text-xs uppercase tracking-widest text-muted-foreground">{t("end_date")}</p><p className="mt-1 font-semibold">{fmtDate(sub.end_date)}</p></div></div></div></> : <div className="panel mt-6 p-8 text-center"><h3 className="text-xl font-bold">{t("no_subscription")}</h3><p className="mt-2 text-sm text-muted-foreground">{t("no_subscription_d")}</p><Button asChild className="mt-5"><Link to="/packages">{t("hero_cta")}</Link></Button></div>}

    <section className="mt-8"><div className="mb-4 flex items-center justify-between"><div><h3 className="flex items-center gap-2 text-xl font-bold"><CreditCard className="size-5 text-primary" /> {pick("Available packages", "الباقات المتاحة")}</h3><p className="mt-1 text-sm text-muted-foreground">{pick("Choose the package that fits your car", "اختر الباقة المناسبة لسيارتك")}</p></div><Button asChild variant="outline" size="sm"><Link to="/packages">{pick("All packages", "كل الباقات")}</Link></Button></div>{activePackages.length === 0 ? <div className="panel p-6 text-sm text-muted-foreground">{pick("No active packages right now.", "لا توجد باقات نشطة حاليًا.")}</div> : <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{activePackages.map(p => <div key={p.id} className="panel p-5"><h4 className="text-lg font-bold">{pick(p.title_en, p.title_ar)}</h4><p className="mt-2 text-sm text-muted-foreground">{pick(p.description_en, p.description_ar)}</p><div className="mt-4 flex items-end justify-between"><span className="text-2xl font-bold">{money(p.price)}</span><span className="text-sm text-muted-foreground">{p.washes_count} {pick("washes", "غسلة")}</span></div><Button asChild className="mt-4 w-full"><Link to="/packages">{pick("View details", "عرض التفاصيل")}</Link></Button></div>)}</div>}</section>
    <section className="mt-8"><div className="mb-4 flex items-center justify-between"><div><h3 className="flex items-center gap-2 text-xl font-bold"><Tag className="size-5 text-primary" /> {pick("Current offers", "العروض الحالية")}</h3><p className="mt-1 text-sm text-muted-foreground">{pick("Latest TapWash offers", "أحدث عروض TapWash")}</p></div><Button asChild variant="outline" size="sm"><Link to="/offers">{pick("All offers", "كل العروض")}</Link></Button></div>{activeOffers.length === 0 ? <div className="panel p-6 text-sm text-muted-foreground">{pick("No active offers right now.", "لا توجد عروض نشطة حاليًا.")}</div> : <div className="grid gap-4 md:grid-cols-2">{activeOffers.slice(0, 4).map(o => <div key={o.id} className="panel p-5"><h4 className="text-lg font-bold">{pick(o.title_en, o.title_ar)}</h4><p className="mt-2 text-sm text-muted-foreground">{pick(o.description_en, o.description_ar)}</p><div className="mt-4 flex items-center gap-3"><span className="text-xl font-bold">{money(o.price)}</span>{o.old_price != null && Number(o.old_price) > Number(o.price) && <span className="text-sm text-muted-foreground line-through">{money(o.old_price)}</span>}</div></div>)}</div>}</section>
    <div className="mt-6 grid gap-3 sm:grid-cols-3"><Button size="lg" onClick={renew}><RefreshCw className="me-1.5 size-4" />{t("renew")}</Button><Button size="lg" variant="outline" asChild disabled={!wa}><a href={wa ? `https://wa.me/${wa}` : "#"} target="_blank" rel="noreferrer"><MessageCircle className="me-1.5 size-4" />{t("whatsapp")}</a></Button><Button size="lg" variant="outline" asChild><a href={`tel:${settings?.phone ?? ""}`}><Phone className="me-1.5 size-4" />{t("call")}</a></Button></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="panel p-6"><h3 className="flex items-center gap-2 text-lg font-bold"><CreditCard className="size-4 text-primary" /> {t("my_cards")}</h3><div className="mt-4 space-y-3">{(cards ?? []).length === 0 && <p className="text-sm text-muted-foreground">{t("empty")}</p>}{(cards ?? []).map(c => <div key={c.id} className="flex items-center justify-between rounded-xl border border-border p-4"><div><p className="font-semibold">{c.card_type === "card" ? t("card") : c.card_type === "sticker" ? t("sticker") : t("keychain")}</p><p className="text-xs text-muted-foreground">{c.serial_number}</p></div><Badge variant="secondary">{fmtDate(c.activation_date)}</Badge></div>)}</div></section><section className="panel p-6"><h3 className="flex items-center gap-2 text-lg font-bold"><Droplets className="size-4 text-primary" /> {t("wash_history")}</h3><div className="mt-4 space-y-3">{(washes ?? []).length === 0 && <p className="text-sm text-muted-foreground">{t("empty")}</p>}{(washes ?? []).map(w => <div key={w.id} className="flex items-center justify-between rounded-xl border border-border p-4 text-sm"><span className="font-medium">{fmtDate(w.washed_at)}</span><span className="text-muted-foreground">{w.branch ?? "—"}</span></div>)}</div></section></div>
  </div></div>;
}