/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCardsRouteImport } from './routes/_authenticated/admin/cards'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin/customers'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin/employees'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin/notifications'
import { Route as AuthenticatedAdminOffersRouteImport } from './routes/_authenticated/admin/offers'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes/_authenticated/admin/packages'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin/pages'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin/subscriptions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCardsRoute = AuthenticatedAdminCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOffersRoute =
  AuthenticatedAdminOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/packages': typeof PackagesRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/cards': typeof AuthenticatedAdminCardsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/packages': typeof PackagesRoute
  '/services': typeof ServicesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/cards': typeof AuthenticatedAdminCardsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/offers': typeof OffersRoute
  '/packages': typeof PackagesRoute
  '/services': typeof ServicesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/cards': typeof AuthenticatedAdminCardsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/offers': typeof AuthenticatedAdminOffersRoute
  '/_authenticated/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/offers'
    | '/packages'
    | '/services'
    | '/admin'
    | '/dashboard'
    | '/admin/cards'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/packages'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/subscriptions'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/offers'
    | '/packages'
    | '/services'
    | '/dashboard'
    | '/admin/cards'
    | '/admin/customers'
    | '/admin/employees'
    | '/admin/notifications'
    | '/admin/offers'
    | '/admin/packages'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/subscriptions'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/login'
    | '/offers'
    | '/packages'
    | '/services'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/cards'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/offers'
    | '/_authenticated/admin/packages'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  OffersRoute: typeof OffersRoute
  PackagesRoute: typeof PackagesRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cards': {
      id: '/_authenticated/admin/cards'
      path: '/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AuthenticatedAdminCardsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/offers': {
      id: '/_authenticated/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AuthenticatedAdminOffersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/packages': {
      id: '/_authenticated/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCardsRoute: typeof AuthenticatedAdminCardsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOffersRoute: typeof AuthenticatedAdminOffersRoute
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCardsRoute: AuthenticatedAdminCardsRoute,
    AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
    AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
    AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
    AuthenticatedAdminOffersRoute: AuthenticatedAdminOffersRoute,
    AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRoute,
    AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  OffersRoute: OffersRoute,
  PackagesRoute: PackagesRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
