-- Reconcile RLS and updated_at triggers for the production schema.

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
drop policy if exists "profiles_update_own_or_admin" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "cars_select_own_or_admin" on public.cars;
drop policy if exists "cars_write_own_or_admin" on public.cars;
drop policy if exists "nfc_select_own_or_admin" on public.nfc_cards;
drop policy if exists "nfc_write_admin" on public.nfc_cards;
drop policy if exists "notifications_select_own_or_admin" on public.notifications;
drop policy if exists "notifications_update_own_or_admin" on public.notifications;
drop policy if exists "subscriptions_select_own_or_admin" on public.subscriptions;
drop policy if exists "subscriptions_write_admin" on public.subscriptions;
drop policy if exists "washes_select_own_or_admin" on public.washes;
drop policy if exists "washes_write_admin" on public.washes;
drop policy if exists "packages_public_read" on public.packages;
drop policy if exists "packages_admin_write" on public.packages;
drop policy if exists "offers_public_read" on public.offers;
drop policy if exists "offers_admin_write" on public.offers;
drop policy if exists "site_pages_public_read" on public.site_pages;
drop policy if exists "site_pages_admin_write" on public.site_pages;
drop policy if exists "site_settings_public_read" on public.site_settings;
drop policy if exists "site_settings_admin_write" on public.site_settings;
drop policy if exists "roles_select_own_or_admin" on public.user_roles;
drop policy if exists "roles_admin_write" on public.user_roles;
drop policy if exists "employees_admin_all" on public.employees;
drop policy if exists "payments_select_own_or_admin" on public.payments;
drop policy if exists "payments_admin_write" on public.payments;

alter table public.profiles enable row level security;
alter table public.cars enable row level security;
alter table public.nfc_cards enable row level security;
alter table public.notifications enable row level security;
alter table public.subscriptions enable row level security;
alter table public.washes enable row level security;
alter table public.packages enable row level security;
alter table public.offers enable row level security;
alter table public.site_pages enable row level security;
alter table public.site_settings enable row level security;
alter table public.user_roles enable row level security;
alter table public.employees enable row level security;
alter table public.payments enable row level security;

create policy "profiles_select_own_or_admin" on public.profiles for select to public using(auth.uid()=id or public.has_role(auth.uid(),'admin'));
create policy "profiles_update_own_or_admin" on public.profiles for update to public using(auth.uid()=id or public.has_role(auth.uid(),'admin')) with check(auth.uid()=id or public.has_role(auth.uid(),'admin'));
create policy "profiles_insert_own" on public.profiles for insert to public with check(auth.uid()=id);
create policy "cars_select_own_or_admin" on public.cars for select to public using(customer_id=auth.uid() or public.has_role(auth.uid(),'admin'));
create policy "cars_write_own_or_admin" on public.cars for all to public using(customer_id=auth.uid() or public.has_role(auth.uid(),'admin')) with check(customer_id=auth.uid() or public.has_role(auth.uid(),'admin'));
create policy "nfc_select_own_or_admin" on public.nfc_cards for select to public using(customer_id=auth.uid() or public.has_role(auth.uid(),'admin'));
create policy "nfc_write_admin" on public.nfc_cards for all to public using(public.has_role(auth.uid(),'admin')) with check(public.has_role(auth.uid(),'admin'));
create policy "notifications_select_own_or_admin" on public.notifications for select to public using(customer_id=auth.uid() or public.has_role(auth.uid(),'admin'));
create policy "notifications_update_own_or_admin" on public.notifications for update to public using(customer_id=auth.uid() or public.has_role(auth.uid(),'admin')) with check(customer_id=auth.uid() or public.has_role(auth.uid(),'admin'));
create policy "subscriptions_select_own_or_admin" on public.subscriptions for select to public using(customer_id=auth.uid() or public.has_role(auth.uid(),'admin'));
create policy "subscriptions_write_admin" on public.subscriptions for all to public using(public.has_role(auth.uid(),'admin')) with check(public.has_role(auth.uid(),'admin'));
create policy "washes_select_own_or_admin" on public.washes for select to public using(customer_id=auth.uid() or public.has_role(auth.uid(),'admin'));
create policy "washes_write_admin" on public.washes for all to public using(public.has_role(auth.uid(),'admin')) with check(public.has_role(auth.uid(),'admin'));
create policy "packages_public_read" on public.packages for select to public using(true);
create policy "packages_admin_write" on public.packages for all to public using(public.has_role(auth.uid(),'admin')) with check(public.has_role(auth.uid(),'admin'));
create policy "offers_public_read" on public.offers for select to public using(true);
create policy "offers_admin_write" on public.offers for all to public using(public.has_role(auth.uid(),'admin')) with check(public.has_role(auth.uid(),'admin'));
create policy "site_pages_public_read" on public.site_pages for select to public using(true);
create policy "site_pages_admin_write" on public.site_pages for all to public using(public.has_role(auth.uid(),'admin')) with check(public.has_role(auth.uid(),'admin'));
create policy "site_settings_public_read" on public.site_settings for select to public using(true);
create policy "site_settings_admin_write" on public.site_settings for all to public using(public.has_role(auth.uid(),'admin')) with check(public.has_role(auth.uid(),'admin'));
create policy "roles_select_own_or_admin" on public.user_roles for select to public using(user_id=auth.uid() or public.has_role(auth.uid(),'admin'));
create policy "roles_admin_write" on public.user_roles for all to public using(public.has_role(auth.uid(),'admin')) with check(public.has_role(auth.uid(),'admin'));
create policy "employees_admin_all" on public.employees for all to public using(public.has_role(auth.uid(),'admin')) with check(public.has_role(auth.uid(),'admin'));
create policy "payments_select_own_or_admin" on public.payments for select to public using(customer_id=auth.uid() or public.has_role(auth.uid(),'admin'));
create policy "payments_admin_write" on public.payments for all to public using(public.has_role(auth.uid(),'admin')) with check(public.has_role(auth.uid(),'admin'));

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists set_profiles_updated_at on public.profiles; create trigger set_profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists set_packages_updated_at on public.packages; create trigger set_packages_updated_at before update on public.packages for each row execute function public.set_updated_at();
drop trigger if exists set_offers_updated_at on public.offers; create trigger set_offers_updated_at before update on public.offers for each row execute function public.set_updated_at();
drop trigger if exists set_subscriptions_updated_at on public.subscriptions; create trigger set_subscriptions_updated_at before update on public.subscriptions for each row execute function public.set_updated_at();
drop trigger if exists set_site_pages_updated_at on public.site_pages; create trigger set_site_pages_updated_at before update on public.site_pages for each row execute function public.set_updated_at();
drop trigger if exists set_site_settings_updated_at on public.site_settings; create trigger set_site_settings_updated_at before update on public.site_settings for each row execute function public.set_updated_at();
drop trigger if exists set_nfc_cards_updated_at on public.nfc_cards; create trigger set_nfc_cards_updated_at before update on public.nfc_cards for each row execute function public.set_updated_at();
drop trigger if exists set_employees_updated_at on public.employees; create trigger set_employees_updated_at before update on public.employees for each row execute function public.set_updated_at();
notify pgrst,'reload schema';
