-- The booking form already stores subscription location data in notes as:
-- address | location_url | optional customer note.
-- Keep the service location isolated from the customer's default location.

create or replace function public.populate_subscription_service_location()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  parts text[];
begin
  if new.service_address is null and new.service_location_url is null and nullif(trim(coalesce(new.notes, '')), '') is not null then
    parts := string_to_array(new.notes, ' | ');
    new.service_address := nullif(trim(coalesce(parts[1], '')), '');
    new.service_location_url := nullif(trim(coalesce(parts[2], '')), '');
  end if;
  return new;
end;
$$;

drop trigger if exists trg_populate_subscription_service_location on public.subscription_requests;
create trigger trg_populate_subscription_service_location
before insert on public.subscription_requests
for each row execute function public.populate_subscription_service_location();

-- Keep existing pending requests consistent where the first two note segments
-- are the address and map URL generated by the booking form.
update public.subscription_requests
set service_address = nullif(trim(split_part(notes, ' | ', 1)), ''),
    service_location_url = nullif(trim(split_part(notes, ' | ', 2)), '')
where service_address is null
  and service_location_url is null
  and notes like '% | %';

grant execute on function public.populate_subscription_service_location() to authenticated;
